(()=>{
'use strict';
const SUPABASE_URL='https://fvzoogbdezueswyihxiz.supabase.co';
const SUPABASE_KEY='sb_publishable_wqrt_5bjmxmE-mw4i6EQbw_I7E_AzaZ';
const STORE='sanabil-auth-session-v2',ROLE_KEY='sanabil-auth-access-v2',USER_ADMIN_FN=`${SUPABASE_URL}/functions/v1/sanabil-user-admin`;
let busy=false;
const get=(k,s=false)=>{try{return(s?sessionStorage:localStorage).getItem(k)}catch{return null}};
const put=(k,v,s=false)=>{try{(s?sessionStorage:localStorage).setItem(k,v)}catch{}};
const del=(k,s=false)=>{try{(s?sessionStorage:localStorage).removeItem(k)}catch{}};
const api=async(url,o={})=>{const r=await fetch(url,{...o,headers:{apikey:SUPABASE_KEY,...(o.headers||{}),'Content-Type':'application/json'}});let b=null;try{b=await r.json()}catch{}if(!r.ok)throw new Error(b?.msg||b?.message||b?.error_description||b?.error||'تعذر الاتصال بالخدمة');return b};
const sess=()=>{const x=get(STORE)||get(STORE,true);try{return x?JSON.parse(x):null}catch{return null}};
const save=(s,t)=>{del(STORE);del(STORE,true);put(STORE,JSON.stringify(s),!t)};
const clear=()=>{del(STORE);del(STORE,true);del(ROLE_KEY);del(ROLE_KEY,true)};
const toast=(m,e=false)=>{let n=document.getElementById('sanabil-auth-toast');if(!n){n=document.createElement('div');n.id='sanabil-auth-toast';Object.assign(n.style,{position:'fixed',left:'18px',right:'18px',bottom:'18px',zIndex:100000,maxWidth:'560px',margin:'auto',padding:'13px 17px',borderRadius:'14px',background:e?'#8b1e2d':'#006b55',color:'#fff',fontWeight:'700',textAlign:'center',direction:'rtl',boxShadow:'0 10px 35px #0003'});document.body.appendChild(n)}n.textContent=m;n.hidden=false;clearTimeout(n._t);n._t=setTimeout(()=>n.hidden=true,4200)};
const fields=()=>({email:document.getElementById('login-email'),password:document.getElementById('login-password'),trusted:document.querySelector('.trusted-device input'),button:[...document.querySelectorAll('button')].find(x=>/دخول/.test(x.textContent||''))});
async function access(token){return await api(`${SUPABASE_URL}/rest/v1/rpc/my_access`,{method:'POST',headers:{Authorization:`Bearer ${token}`},body:'{}'})||{}}
function validAccess(a){const roles=Array.isArray(a?.roles)?a.roles.map(x=>String(x).toLowerCase()):[];return a?.active===true&&roles.some(r=>['admin','supervisor','teacher'].includes(r))}
const NAV_BY_ROLE={teacher:new Set(['الرئيسية','البصمة','الحصيلة اليومية','الاختبارات']),supervisor:new Set(['الرئيسية','الخطط التعليمية','الاختبارات','الطلاب والمعلمون','الاستعلامات','التقارير والإحصاءات']),admin:new Set(['الرئيسية','الخطط التعليمية','الاختبارات','الطلاب والمعلمون','الاستعلامات','التقارير والإحصاءات','إعدادات المنصة','إدارة الكوادر'])};
const canonical=x=>String(x||'').replace(/\s+/g,' ').trim().replace(/^(إدارة|صفحة)\s+/,'');
function currentRole(){try{const a=JSON.parse(get(ROLE_KEY)||get(ROLE_KEY,true)||'{}'),rs=Array.isArray(a.roles)?a.roles.map(x=>String(x).toLowerCase()):[];return rs.includes('admin')?'admin':rs.includes('supervisor')?'supervisor':rs.includes('teacher')?'teacher':null}catch{return null}}
function roleAllows(label,role){return !role||NAV_BY_ROLE[role].has(canonical(label))}
function enforceRoleUi(){const role=currentRole();if(!role||document.getElementById('login-email'))return;document.querySelectorAll('.tabs button').forEach(b=>{const allowed=roleAllows(b.textContent,role);b.hidden=!allowed;b.setAttribute('aria-hidden',String(!allowed));b.style.display=allowed?'':'none'});document.querySelectorAll('button,[role="button"],a').forEach(el=>{const label=canonical(el.textContent);if(!label)return;if(role==='teacher'&&/الطلاب والمعلمون|التقارير|الإحصاءات|الإعدادات|الخطط|الاستعلامات/.test(label)&&!el.closest('.tabs')){el.hidden=true;el.style.display='none'}if((role==='supervisor'||role==='admin')&&/الحضور والبصمة|البصمة|الحصيلة اليومية|الحصيلة/.test(label)&&!el.closest('.tabs')){el.hidden=true;el.style.display='none'}})}
let roleUiTimer=null;function scheduleRoleUi(){clearTimeout(roleUiTimer);roleUiTimer=setTimeout(enforceRoleUi,40)}function installRoleObserver(){if(window.__sanabilRoleObserver)return;window.__sanabilRoleObserver=new MutationObserver(scheduleRoleUi);window.__sanabilRoleObserver.observe(document.body,{childList:true,subtree:true});scheduleRoleUi()}
function adminTools(){if(currentRole()!=='admin'||document.getElementById('sanabil-admin-add-user'))return;const b=document.createElement('button');b.id='sanabil-admin-add-user';b.type='button';b.className='sanabil-admin-users-btn';b.textContent='➕ إضافة مستخدم جديد';b.title='إنشاء حساب مدير أو مشرف أو معلم';Object.assign(b.style,{position:'fixed',top:'18px',left:'18px',zIndex:99999,border:0,borderRadius:'14px',padding:'11px 16px',background:'#006b55',color:'#fff',fontWeight:'800',fontSize:'15px',cursor:'pointer',boxShadow:'0 8px 24px #0003'});b.onclick=()=>openUsers();document.body.appendChild(b)}
async function fn(action,payload={}){const s=sess();if(!s?.access_token)throw Error('انتهت جلسة الدخول، أعد تسجيل الدخول');return await api(USER_ADMIN_FN,{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({action,...payload})})}
const css=`#sanabil-users-modal{position:fixed;inset:0;background:#0008;z-index:100001;display:flex;align-items:center;justify-content:center;padding:14px;direction:rtl}#sanabil-users-card{background:#fff;color:#18312f;width:min(980px,100%);max-height:92vh;overflow:auto;border-radius:22px;padding:20px;box-shadow:0 20px 60px #0005}#sanabil-users-card h2{margin:0 0 12px;color:#006b55}#sanabil-users-card input,#sanabil-users-card select{width:100%;box-sizing:border-box;padding:11px;border:1px solid #ccd8d4;border-radius:10px;background:#fff}#sanabil-users-card .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.sanabil-user-row{border:1px solid #dde6e3;border-radius:13px;padding:11px;margin:8px 0;display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.sanabil-user-actions{display:flex;gap:6px;flex-wrap:wrap}.sanabil-user-actions button,#sanabil-users-card .primary,#sanabil-users-card .secondary{border:0;border-radius:10px;padding:9px 13px;font-weight:800;cursor:pointer}.sanabil-user-actions button,#sanabil-users-card .primary{background:#006b55;color:#fff}.sanabil-user-actions .danger{background:#8b1e2d;color:#fff}.sanabil-user-actions .secondary,#sanabil-users-card .secondary{background:#eef3f1;color:#16423b}@media(max-width:650px){#sanabil-users-card .grid{grid-template-columns:1fr}.sanabil-user-row{grid-template-columns:1fr}}`;
let scopeCache={complexes:[],circles:[]};
const activeMembership=u=>{const a=Array.isArray(u?.memberships)?u.memberships:(u?.memberships?[u.memberships]:[]);return a.find(x=>x?.active)!==undefined?a.find(x=>x?.active):(a[0]||{})};
const scopeLabel=(ms={})=>{if(!ms?.role)return '—';const r=String(ms.role).toLowerCase();if(r==='admin')return 'جميع المجمعات';if(r==='supervisor')return scopeCache.complexes.find(x=>x.id===ms.complex_id)?.name||ms.complex_id||'—';if(r==='teacher'){const cx=scopeCache.complexes.find(x=>x.id===ms.complex_id)?.name||ms.complex_id||'—',ci=scopeCache.circles.find(x=>x.id===ms.circle_id)?.name||ms.circle_id||'—';return cx+' · '+ci}return '—'};
function fillScopes(role,complexValue='',circleValue=''){const cx=document.getElementById('su-complex'),ci=document.getElementById('su-circle');if(!cx||!ci)return;const isAdmin=role==='admin',isTeacher=role==='teacher';cx.disabled=isAdmin;ci.disabled=!isTeacher;cx.innerHTML='<option value="">اختر المجمع</option>'+scopeCache.complexes.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join('');if(complexValue)cx.value=complexValue;const selected=cx.value||complexValue;const circles=scopeCache.circles.filter(x=>!selected||x.complex_id===selected);ci.innerHTML='<option value="">اختر الحلقة</option>'+circles.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join('');if(circleValue)ci.value=circleValue}
async function loadScopes(){try{const r=await fn('scopes');scopeCache={complexes:Array.isArray(r.complexes)?r.complexes:[],circles:Array.isArray(r.circles)?r.circles:[]};const role=document.getElementById('su-role')?.value||'teacher';fillScopes(role,document.getElementById('su-complex')?.value||'',document.getElementById('su-circle')?.value||'')}catch(e){toast(e.message||'تعذر تحميل المجمعات والحلقات.',true)}}
function resetUserForm(){const card=document.getElementById('sanabil-users-card');if(!card)return;card.dataset.editId='';['su-name','su-email','su-phone','su-pw'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});const email=document.getElementById('su-email'),pw=document.getElementById('su-pw'),role=document.getElementById('su-role'),btn=document.getElementById('su-create'),cancel=document.getElementById('su-cancel');if(email)email.disabled=false;if(pw){pw.disabled=false;pw.placeholder='كلمة المرور المؤقتة (8 أحرف فأكثر)'}if(role)role.value='teacher';if(btn)btn.textContent='إنشاء الحساب';if(cancel)cancel.hidden=true;fillScopes('teacher')}
function openUsers(){if(document.getElementById('sanabil-users-modal'))return;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);const m=document.createElement('div');m.id='sanabil-users-modal';m.innerHTML=`<div id="sanabil-users-card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><h2>إدارة الكوادر</h2><button class="secondary" id="sanabil-users-close">إغلاق</button></div><p style="margin-top:0">إنشاء حسابات المديرين والمشرفين والمعلمين وربطها بالسجلات الفعلية للمجمعات والحلقات.</p><section style="border-top:1px solid #e2e9e7;padding-top:14px"><h3 id="su-form-title">إضافة مستخدم جديد</h3><div class="grid"><input id="su-name" placeholder="الاسم الكامل"><input id="su-email" type="email" placeholder="البريد الإلكتروني"><input id="su-phone" placeholder="رقم الجوال (اختياري)"><input id="su-pw" type="text" placeholder="كلمة المرور المؤقتة (8 أحرف فأكثر)"><select id="su-role"><option value="teacher">معلم</option><option value="supervisor">مشرف مجمع</option><option value="admin">مدير النظام</option></select><select id="su-complex"><option value="">جارٍ تحميل المجمعات...</option></select><select id="su-circle"><option value="">جارٍ تحميل الحلقات...</option></select></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px"><button class="primary" id="su-create">إنشاء الحساب</button><button class="secondary" id="su-cancel" hidden>إلغاء التعديل</button></div></section><section style="border-top:1px solid #e2e9e7;margin-top:18px;padding-top:14px"><h3>المستخدمون الحاليون</h3><div id="su-list">جارٍ التحميل...</div></section></div>`;document.body.appendChild(m);document.getElementById('sanabil-users-close').onclick=()=>m.remove();document.getElementById('su-role').onchange=e=>fillScopes(e.target.value);document.getElementById('su-complex').onchange=()=>fillScopes(document.getElementById('su-role').value,document.getElementById('su-complex').value);document.getElementById('su-create').onclick=saveUser;document.getElementById('su-cancel').onclick=resetUserForm;loadScopes().then(loadUsers)}
async function loadUsers(){const box=document.getElementById('su-list');if(!box)return;try{const r=await fn('list');if(Array.isArray(r.complexes))scopeCache.complexes=r.complexes;if(Array.isArray(r.circles))scopeCache.circles=r.circles;box.innerHTML='';(r.users||[]).forEach(u=>{const ms=activeMembership(u),role=String(ms.role||u.role||'').toLowerCase(),roleAr={admin:'مدير النظام',supervisor:'مشرف مجمع',teacher:'معلم'}[role]||role;const row=document.createElement('div');row.className='sanabil-user-row';row.innerHTML=`<div><strong>${esc(u.display_name||'بدون اسم')}</strong><div style="font-size:.9em;opacity:.78">${esc(u.email||'')} · ${esc(roleAr)} · ${esc(scopeLabel({...ms,role}))} · ${u.active?'نشط':'معطل'}</div></div><div class="sanabil-user-actions"><button data-edit="${u.id}">تعديل</button><button class="${u.active?'danger':''}" data-toggle="${u.id}">${u.active?'تعطيل':'تفعيل'}</button></div>`;row.querySelector('[data-edit]').onclick=()=>editUser(u,ms);row.querySelector('[data-toggle]').onclick=()=>toggleUser(u,ms);box.appendChild(row)});if(!(r.users||[]).length)box.textContent='لا يوجد مستخدمون بعد.'}catch(e){box.textContent=e.message||'تعذر تحميل المستخدمين'}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function saveUser(){const card=document.getElementById('sanabil-users-card'),editId=card?.dataset.editId||'',name=document.getElementById('su-name').value.trim(),email=document.getElementById('su-email').value.trim(),phone=document.getElementById('su-phone').value.trim(),password=document.getElementById('su-pw').value,role=document.getElementById('su-role').value,complex_id=document.getElementById('su-complex').value||null,circle_id=document.getElementById('su-circle').value||null;if(!name||(!editId&&!email)||(!editId&&!password)){toast('أكمل الاسم والبريد وكلمة المرور.',true);return}if(role==='supervisor'&&!complex_id){toast('اختر المجمع للمشرف.',true);return}if(role==='teacher'&&(!complex_id||!circle_id)){toast('اختر المجمع والحلقة للمعلم.',true);return}const b=document.getElementById('su-create');b.disabled=true;try{if(editId){await fn('update',{user_id:editId,display_name:name,phone,role,complex_id:role==='admin'?null:complex_id,circle_id:role==='teacher'?circle_id:null,active:true});toast('تم تحديث بيانات المستخدم.')}else{await fn('create',{display_name:name,email,phone,password,role,complex_id:role==='admin'?null:complex_id,circle_id:role==='teacher'?circle_id:null});toast('تم إنشاء الحساب وتفعيله بنجاح.')}resetUserForm();await loadUsers()}catch(e){toast(e.message||'تعذر حفظ المستخدم.',true)}finally{b.disabled=false}}
function editUser(u,ms){const card=document.getElementById('sanabil-users-card');if(!card)return;const role=String(ms.role||u.role||'teacher').toLowerCase();card.dataset.editId=u.id;document.getElementById('su-name').value=u.display_name||'';document.getElementById('su-email').value=u.email||'';document.getElementById('su-email').disabled=true;document.getElementById('su-phone').value=u.phone||'';document.getElementById('su-pw').value='';document.getElementById('su-pw').disabled=true;document.getElementById('su-pw').placeholder='لا تتغير كلمة المرور من هذه الشاشة';document.getElementById('su-role').value=role;fillScopes(role,ms.complex_id||'',ms.circle_id||'');document.getElementById('su-create').textContent='حفظ التعديل';document.getElementById('su-cancel').hidden=false;document.getElementById('su-form-title').textContent='تعديل المستخدم';card.scrollTo({top:0,behavior:'smooth'})}
async function toggleUser(u,ms){const next=!u.active;if(!confirm(`${next?'تفعيل':'تعطيل'} حساب ${u.display_name||u.email}؟`))return;const role=String(ms.role||u.role||'teacher').toLowerCase();try{await fn('update',{user_id:u.id,role,complex_id:role==='admin'?null:(ms.complex_id||null),circle_id:role==='teacher'?(ms.circle_id||null):null,active:next});toast(next?'تم تفعيل الحساب.':'تم تعطيل الحساب.');loadUsers()}catch(e){toast(e.message||'تعذر تغيير حالة الحساب.',true)}}
async function signIn(email,password,trusted){const t=await api(`${SUPABASE_URL}/auth/v1/token?grant_type=password`,{method:'POST',body:JSON.stringify({email,password})});const u=await api(`${SUPABASE_URL}/auth/v1/user`,{headers:{Authorization:`Bearer ${t.access_token}`}});const a=await access(t.access_token);if(!validAccess(a))throw Error('تم التحقق من الحساب، لكن لا توجد صلاحية فعالة في منصة سنابل الوحي.');save({access_token:t.access_token,refresh_token:t.refresh_token,expires_at:Date.now()+Number(t.expires_in||3600)*1000,user_id:u.id},trusted);put(ROLE_KEY,JSON.stringify(a),!trusted)}
async function refresh(s,t){const x=await api(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',body:JSON.stringify({refresh_token:s.refresh_token})});save({access_token:x.access_token,refresh_token:x.refresh_token||s.refresh_token,expires_at:Date.now()+Number(x.expires_in||3600)*1000,user_id:s.user_id},t)}
function enter(){const {button}=fields();if(button){button.dataset.authApproved='1';button.click()}}
async function restore(){const s=sess();if(!s)return;const trusted=!!get(STORE);try{if(s.expires_at&&Date.now()>s.expires_at-30000)await refresh(s,trusted);const current=sess(),a=await access(current.access_token);if(!validAccess(a)){clear();return}put(ROLE_KEY,JSON.stringify(a),!trusted);await api(`${SUPABASE_URL}/auth/v1/user`,{headers:{Authorization:`Bearer ${current.access_token}`}});enter()}catch{clear()}}
document.addEventListener('click',async ev=>{const b=ev.target.closest('button,a,[role="button"]');if(!b)return;const label=(b.textContent||'').replace(/\s+/g,' ').trim(),role=currentRole();if(role&&!document.getElementById('login-email')){const forbiddenTeacher=role==='teacher'&&/الطلاب والمعلمون|التقارير|الإحصاءات|الإعدادات|الخطط|الاستعلامات/.test(label),forbiddenManager=(role==='supervisor'||role==='admin')&&/إدخال الحضور|تسجيل الحضور|إدخال الحصيلة|الحصيلة اليومية للمعلم|الحصيلة/.test(label);if(forbiddenTeacher||forbiddenManager){ev.preventDefault();ev.stopImmediatePropagation();toast('هذه الوظيفة غير متاحة لهذا الدور.',true);return}}if(/دخول/.test(label)&&document.getElementById('login-email')){if(b.dataset.authApproved==='1'){delete b.dataset.authApproved;setTimeout(installRoleObserver,80);return}ev.preventDefault();ev.stopImmediatePropagation();if(busy)return;const {email,password,trusted}=fields();if(!email?.value||!password?.value){toast('أدخل البريد الإلكتروني وكلمة المرور.',true);return}busy=true;b.disabled=true;b.textContent='جارٍ التحقق...';try{await signIn(email.value.trim(),password.value,trusted?.checked!==false);toast('تم تسجيل الدخول والتحقق من الصلاحيات.');setTimeout(enter,120)}catch(e){toast(e.message||'بيانات الدخول غير صحيحة.',true)}finally{busy=false;b.disabled=false;b.textContent='دخول'} }else if(/تسجيل الخروج|خروج/.test(label)&&!document.getElementById('login-email')){clear();location.reload()}},true);
function polishLoginCopy(){const email=document.getElementById('login-email');if(!email)return;const b=[...document.querySelectorAll('button')].find(x=>/دخول/.test(x.textContent||''));if(b&&!busy)b.textContent='تسجيل الدخول';const note=document.querySelector('.login-note');if(note)note.textContent='يتم التحقق من الحساب والصلاحيات مباشرة عبر Supabase، وتبقى الجلسة محفوظة على الجهاز الموثوق.'}
window.addEventListener('load',()=>{polishLoginCopy();setTimeout(polishLoginCopy,900);setTimeout(restore,250);setTimeout(()=>{installRoleObserver();adminTools()},700);setInterval(()=>{if(currentRole()==='admin')adminTools()},700)});
})();
