(()=>{
'use strict';
const SUPABASE_URL='https://fvzoogbdezueswyihxiz.supabase.co';
const SUPABASE_KEY='sb_publishable_wqrt_5bjmxmE-mw4i6EQbw_I7E_AzaZ';
const SESSION_KEY='sanabil-auth';
const FN=`${SUPABASE_URL}/functions/v1/sanabil-user-admin`;
let scopeCache={complexes:[],circles:[]}, adminState=false, checking=false;

const readRaw=k=>{for(const s of [localStorage,sessionStorage]){try{const v=s.getItem(k);if(v)return v}catch{}}return null};
const readSession=()=>{try{const x=JSON.parse(readRaw(SESSION_KEY)||'null');return x&&x.access_token?x:null}catch{return null}};
const cleanupLegacy=()=>{for(const s of [localStorage,sessionStorage]){try{s.removeItem('sanabil-auth-session-v2');s.removeItem('sanabil-auth-access-v2')}catch{}}};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const toast=(m,e=false)=>{let n=document.getElementById('sanabil-admin-toast');if(!n){n=document.createElement('div');n.id='sanabil-admin-toast';Object.assign(n.style,{position:'fixed',left:'18px',right:'18px',bottom:'18px',zIndex:100005,maxWidth:'560px',margin:'auto',padding:'13px 17px',borderRadius:'14px',color:'#fff',fontWeight:'700',textAlign:'center',direction:'rtl',boxShadow:'0 10px 35px #0003'});document.body.appendChild(n)}n.style.background=e?'#8b1e2d':'#006b55';n.textContent=m;n.hidden=false;clearTimeout(n._t);n._t=setTimeout(()=>n.hidden=true,3800)};
async function req(url,o={}){const r=await fetch(url,{...o,headers:{apikey:SUPABASE_KEY,...(o.headers||{}),'Content-Type':'application/json'}});let b={};try{b=await r.json()}catch{}if(!r.ok)throw Error(b?.msg||b?.message||b?.error_description||b?.error||'تعذر الاتصال بالخدمة');return b}
async function access(){const s=readSession();if(!s?.access_token)return null;try{return await req(`${SUPABASE_URL}/rest/v1/rpc/my_access`,{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`},body:'{}'})}catch{return null}}
async function call(action,payload={}){const s=readSession();if(!s?.access_token)throw Error('انتهت جلسة الدخول، أعد تسجيل الدخول');return await req(FN,{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`},body:JSON.stringify({action,...payload})})}
async function detectAdmin(){if(checking)return adminState;checking=true;try{const a=await access(),roles=Array.isArray(a?.roles)?a.roles.map(x=>String(x).toLowerCase()):[];adminState=a?.active===true&&roles.includes('admin');return adminState}finally{checking=false}}
function removeButton(){document.getElementById('sanabil-admin-add-user')?.remove()}
function addButton(){if(document.getElementById('sanabil-admin-add-user'))return;const b=document.createElement('button');b.id='sanabil-admin-add-user';b.type='button';b.textContent='➕ إدارة الكوادر';b.title='إدارة حسابات سنابل الوحي';Object.assign(b.style,{position:'fixed',top:'18px',left:'18px',zIndex:99999,border:0,borderRadius:'14px',padding:'11px 16px',background:'#006b55',color:'#fff',fontWeight:'800',fontSize:'15px',cursor:'pointer',boxShadow:'0 8px 24px #0003'});b.onclick=openUsers;document.body.appendChild(b)}
async function syncAdminButton(){if(await detectAdmin())addButton();else removeButton()}
const css=`#sanabil-users-modal{position:fixed;inset:0;background:#0008;z-index:100001;display:flex;align-items:center;justify-content:center;padding:14px;direction:rtl}#sanabil-users-card{background:#fff;color:#18312f;width:min(980px,100%);max-height:92vh;overflow:auto;border-radius:22px;padding:20px;box-shadow:0 20px 60px #0005}#sanabil-users-card h2{margin:0 0 12px;color:#006b55}#sanabil-users-card input,#sanabil-users-card select{width:100%;box-sizing:border-box;padding:11px;border:1px solid #ccd8d4;border-radius:10px;background:#fff}#sanabil-users-card .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.sanabil-user-row{border:1px solid #dde6e3;border-radius:13px;padding:11px;margin:8px 0;display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.sanabil-user-actions{display:flex;gap:6px;flex-wrap:wrap}.sanabil-user-actions button,#sanabil-users-card .primary,#sanabil-users-card .secondary{border:0;border-radius:10px;padding:9px 13px;font-weight:800;cursor:pointer}.sanabil-user-actions button,#sanabil-users-card .primary{background:#006b55;color:#fff}.sanabil-user-actions .danger{background:#8b1e2d;color:#fff}.sanabil-user-actions .secondary,#sanabil-users-card .secondary{background:#eef3f1;color:#16423b}@media(max-width:650px){#sanabil-users-card .grid{grid-template-columns:1fr}.sanabil-user-row{grid-template-columns:1fr}}`;
const activeMembership=u=>{const a=Array.isArray(u?.memberships)?u.memberships:(u?.memberships?[u.memberships]:[]);return a.find(x=>x?.active)??a[0]??{}};
const scopeLabel=(ms={})=>{const r=String(ms?.role||'').toLowerCase();if(r==='admin')return 'جميع المجمعات';if(r==='supervisor')return scopeCache.complexes.find(x=>x.id===ms.complex_id)?.name||ms.complex_id||'—';if(r==='teacher'){const cx=scopeCache.complexes.find(x=>x.id===ms.complex_id)?.name||ms.complex_id||'—',ci=scopeCache.circles.find(x=>x.id===ms.circle_id)?.name||ms.circle_id||'—';return cx+' · '+ci}return '—'};
function fillScopes(role,complexValue='',circleValue=''){const cx=document.getElementById('su-complex'),ci=document.getElementById('su-circle');if(!cx||!ci)return;cx.disabled=role==='admin';ci.disabled=role!=='teacher';cx.innerHTML='<option value="">اختر المجمع</option>'+scopeCache.complexes.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join('');if(complexValue)cx.value=complexValue;const selected=cx.value||complexValue;const circles=scopeCache.circles.filter(x=>!selected||x.complex_id===selected);ci.innerHTML='<option value="">اختر الحلقة</option>'+circles.map(x=>'<option value="'+esc(x.id)+'">'+esc(x.name)+'</option>').join('');if(circleValue)ci.value=circleValue}
async function loadScopes(){const r=await call('scopes');scopeCache={complexes:Array.isArray(r.complexes)?r.complexes:[],circles:Array.isArray(r.circles)?r.circles:[]};fillScopes(document.getElementById('su-role')?.value||'teacher')}
function resetForm(){const card=document.getElementById('sanabil-users-card');if(!card)return;card.dataset.editId='';['su-name','su-email','su-phone','su-pw'].forEach(id=>{const el=document.getElementById(id);if(el)el.value=''});document.getElementById('su-email').disabled=false;document.getElementById('su-pw').disabled=false;document.getElementById('su-pw').placeholder='كلمة المرور المؤقتة (8 أحرف فأكثر)';document.getElementById('su-role').value='teacher';document.getElementById('su-create').textContent='إنشاء الحساب';document.getElementById('su-cancel').hidden=true;document.getElementById('su-form-title').textContent='إضافة مستخدم جديد';fillScopes('teacher')}
function openUsers(){if(document.getElementById('sanabil-users-modal'))return;const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);const m=document.createElement('div');m.id='sanabil-users-modal';m.innerHTML=`<div id="sanabil-users-card"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><h2>إدارة الكوادر</h2><button class="secondary" id="sanabil-users-close">إغلاق</button></div><p style="margin-top:0">إنشاء وتعديل حسابات المديرين والمشرفين والمعلمين وربطها بالمجمعات والحلقات الفعلية.</p><section style="border-top:1px solid #e2e9e7;padding-top:14px"><h3 id="su-form-title">إضافة مستخدم جديد</h3><div class="grid"><input id="su-name" placeholder="الاسم الكامل"><input id="su-email" type="email" placeholder="البريد الإلكتروني"><input id="su-phone" placeholder="رقم الجوال (اختياري)"><input id="su-pw" type="password" placeholder="كلمة المرور المؤقتة (8 أحرف فأكثر)"><select id="su-role"><option value="teacher">معلم</option><option value="supervisor">مشرف مجمع</option><option value="admin">مدير النظام</option></select><select id="su-complex"><option value="">جارٍ تحميل المجمعات...</option></select><select id="su-circle"><option value="">جارٍ تحميل الحلقات...</option></select></div><div style="display:flex;gap:8px;flex-wrap:wrap;margin-top:10px"><button class="primary" id="su-create">إنشاء الحساب</button><button class="secondary" id="su-cancel" hidden>إلغاء التعديل</button></div></section><section style="border-top:1px solid #e2e9e7;margin-top:18px;padding-top:14px"><h3>المستخدمون الحاليون</h3><div id="su-list">جارٍ التحميل...</div></section></div>`;document.body.appendChild(m);m.querySelector('#sanabil-users-close').onclick=()=>m.remove();m.querySelector('#su-role').onchange=e=>fillScopes(e.target.value,m.querySelector('#su-complex').value,m.querySelector('#su-circle').value);m.querySelector('#su-complex').onchange=()=>fillScopes(m.querySelector('#su-role').value,m.querySelector('#su-complex').value,'');m.querySelector('#su-create').onclick=saveUser;m.querySelector('#su-cancel').onclick=resetForm;loadScopes().then(loadUsers).catch(e=>toast(e.message||'تعذر تحميل بيانات الكوادر.',true))}
async function loadUsers(){const box=document.getElementById('su-list');if(!box)return;try{const r=await call('list');if(Array.isArray(r.complexes))scopeCache.complexes=r.complexes;if(Array.isArray(r.circles))scopeCache.circles=r.circles;box.innerHTML='';(r.users||[]).forEach(u=>{const ms=activeMembership(u),role=String(ms.role||u.role||'').toLowerCase(),roleAr={admin:'مدير النظام',supervisor:'مشرف مجمع',teacher:'معلم'}[role]||role||'غير محدد';const row=document.createElement('div');row.className='sanabil-user-row';row.innerHTML=`<div><strong>${esc(u.display_name||'بدون اسم')}</strong><div style="font-size:.9em;opacity:.78">${esc(u.email||'')} · ${esc(roleAr)} · ${esc(scopeLabel({...ms,role}))} · ${u.active?'نشط':'معطل'}</div></div><div class="sanabil-user-actions"><button data-edit="${u.id}">تعديل</button><button class="${u.active?'danger':''}" data-toggle="${u.id}">${u.active?'تعطيل':'تفعيل'}</button></div>`;row.querySelector('[data-edit]').onclick=()=>editUser(u,ms);row.querySelector('[data-toggle]').onclick=()=>toggleUser(u,ms);box.appendChild(row)});if(!(r.users||[]).length)box.textContent='لا يوجد مستخدمون بعد.'}catch(e){box.textContent=e.message||'تعذر تحميل المستخدمين'}}
async function saveUser(){const card=document.getElementById('sanabil-users-card'),editId=card?.dataset.editId||'',name=document.getElementById('su-name').value.trim(),email=document.getElementById('su-email').value.trim(),phone=document.getElementById('su-phone').value.trim(),password=document.getElementById('su-pw').value,role=document.getElementById('su-role').value,complex_id=document.getElementById('su-complex').value||null,circle_id=document.getElementById('su-circle').value||null;if(!name||(!editId&&!email)||(!editId&&!password)){toast('أكمل الاسم والبريد وكلمة المرور.',true);return}if(role==='supervisor'&&!complex_id){toast('اختر المجمع للمشرف.',true);return}if(role==='teacher'&&(!complex_id||!circle_id)){toast('اختر المجمع والحلقة للمعلم.',true);return}const b=document.getElementById('su-create');b.disabled=true;try{if(editId){await call('update',{user_id:editId,display_name:name,phone,role,complex_id:role==='admin'?null:complex_id,circle_id:role==='teacher'?circle_id:null,active:true});toast('تم تحديث بيانات المستخدم.')}else{await call('create',{display_name:name,email,phone,password,role,complex_id:role==='admin'?null:complex_id,circle_id:role==='teacher'?circle_id:null});toast('تم إنشاء الحساب وتفعيله بنجاح.')}resetForm();await loadUsers()}catch(e){toast(e.message||'تعذر حفظ المستخدم.',true)}finally{b.disabled=false}}
function editUser(u,ms){const card=document.getElementById('sanabil-users-card');if(!card)return;const role=String(ms.role||u.role||'teacher').toLowerCase();card.dataset.editId=u.id;document.getElementById('su-name').value=u.display_name||'';document.getElementById('su-email').value=u.email||'';document.getElementById('su-email').disabled=true;document.getElementById('su-phone').value=u.phone||'';document.getElementById('su-pw').value='';document.getElementById('su-pw').disabled=true;document.getElementById('su-pw').placeholder='لا تتغير كلمة المرور من هذه الشاشة';document.getElementById('su-role').value=role;fillScopes(role,ms.complex_id||'',ms.circle_id||'');document.getElementById('su-create').textContent='حفظ التعديل';document.getElementById('su-cancel').hidden=false;document.getElementById('su-form-title').textContent='تعديل المستخدم';card.scrollTo({top:0,behavior:'smooth'})}
async function toggleUser(u,ms){const next=!u.active;if(!confirm(`${next?'تفعيل':'تعطيل'} حساب ${u.display_name||u.email}؟`))return;const role=String(ms.role||u.role||'teacher').toLowerCase();try{await call('update',{user_id:u.id,role,complex_id:role==='admin'?null:(ms.complex_id||null),circle_id:role==='teacher'?(ms.circle_id||null):null,active:next});toast(next?'تم تفعيل الحساب.':'تم تعطيل الحساب.');loadUsers()}catch(e){toast(e.message||'تعذر تغيير حالة الحساب.',true)}}
cleanupLegacy();
window.addEventListener('load',()=>{setTimeout(syncAdminButton,500);setTimeout(syncAdminButton,1600);setInterval(syncAdminButton,5000)});
})();