/* Sanabil live modules. All reads and writes use the signed-in SDK and database RLS. */
(()=>{'use strict';
const titles={dashboard:'الرئيسية',students:'الطلاب والمعلمون',outcomes:'الحصيلة اليومية',plans:'الخطط التعليمية',attendance:'الحضور والبصمة',tests:'الاختبارات',inquiries:'الاستعلامات',reports:'التقارير والإحصاءات',settings:'إعدادات المنصة'};
const roles={admin:'مدير النظام',supervisor:'مشرف مجمع',teacher:'معلم',examiner:'مختبر'};
const sb=()=>{if(!window.supabaseClient)throw Error('جارٍ تهيئة الاتصال، أعد المحاولة.');return window.supabaseClient};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Riyadh',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const result=async q=>{const r=await q;if(r.error)throw Error(r.error.message);return r.data};
const rpc=(name,args)=>result(sb().rpc(name,args));
const rows=async(table,select='*',filters={})=>{let all=[];for(let offset=0;;offset+=500){let q=sb().from(table).select(select).order('id').range(offset,offset+499);for(const [k,v] of Object.entries(filters))q=q.eq(k,v);const data=await result(q);all.push(...data);if(data.length<500)return all;}};
const access=async()=>{const a=await rpc('my_access',{});if(!a?.active)throw Error('الحساب غير نشط؛ راجع مدير النظام.');window.SanabilAccessSync?.(a);return a};
const msg=(root,text,bad=false)=>{let el=root.querySelector('.sl-message');if(!el){el=document.createElement('p');el.className='sl-message';el.setAttribute('role','status');root.prepend(el)}el.textContent=text;el.style.color=bad?'#982431':'#006b55';};
const action=(root,button,fn)=>{button.addEventListener('click',async()=>{if(button.disabled)return;button.disabled=true;try{await fn()}catch(e){msg(root,e.message||'تعذر تنفيذ العملية',true)}finally{button.disabled=false}})};
const button=(label,id='')=>`<button type="button" class="button button-soft" ${id?`data-action="${id}"`:''}>${esc(label)}</button>`;
const field=(label,name,type='text',value='',extra='')=>`<label>${esc(label)}<input name="${name}" type="${type}" value="${esc(value)}" ${extra}></label>`;
const select=(label,name,items,value='',empty='اختر')=>`<label>${esc(label)}<select name="${name}"><option value="">${esc(empty)}</option>${items.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(value)?'selected':''}>${esc(x.name)}</option>`).join('')}</select></label>`;
const table=(headers,data)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${data.length?data.map(row=>`<tr>${row.map(v=>`<td>${v}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}">لا توجد سجلات مطابقة.</td></tr>`}</tbody></table></div>`;
const val=(root,name)=>root.querySelector(`[name="${name}"]`).value;
const dateText=d=>d?new Date(d).toLocaleString('ar-SA',{timeZone:'Asia/Riyadh',dateStyle:'short',timeStyle:'short'}):'—';
const attendanceAr={present:'حاضر',late:'متأخر',excused:'مستأذن',absent:'غائب'};
const qref=r=>r?(`${r.surahName||r.surah||'سورة'}: ${r.ayahNo||r.ayah||''}${r.pageNo?' (ص '+r.pageNo+')':''}`):'—';
const assignmentText=a=>a?`${qref(a.from)} ← ${qref(a.to)}${Number(a.carryIn||0)>0?' · يشمل مرحلًا '+a.carryIn:''}`:'لا يوجد مقرر';
const inlineSelect=(name,items,value='',aria='')=>`<select name="${name}" aria-label="${esc(aria||name)}"><option value="">اختر</option>${items.map(x=>`<option value="${esc(x.id)}" ${String(x.id)===String(value)?'selected':''}>${esc(x.name)}</option>`).join('')}</select>`;
const waPhone=p=>{let d=String(p||'').replace(/\D/g,'');if(d.startsWith('00'))d=d.slice(2);if(d.startsWith('0')&&d.length===10)d='966'+d.slice(1);return d};
const openMushaf=a=>{const r=a?.from;if(!r?.surahNo)return;window.open(`https://quran.com/${r.surahNo}/${r.ayahNo||1}`,'_blank','noopener,noreferrer')};
const wrapCanvas=(ctx,text,x,y,maxWidth,lineHeight)=>{const words=String(text||'').split(/\s+/);let line='',yy=y;for(const w of words){const test=line?line+' '+w:w;if(ctx.measureText(test).width>maxWidth&&line){ctx.fillText(line,x,yy);yy+=lineHeight;line=w}else line=test}if(line){ctx.fillText(line,x,yy);yy+=lineHeight}return yy};
async function shareOutcomeImage(student,date,lesson,recent,review,grade,attendance,note){
  const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=1350;const ctx=canvas.getContext('2d');
  ctx.fillStyle='#f8f5ee';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.direction='rtl';ctx.textAlign='right';
  ctx.fillStyle='#00808A';ctx.fillRect(0,0,1080,180);ctx.fillStyle='#fff';ctx.font='700 54px sans-serif';ctx.fillText('سنابل الوحي',980,95);
  ctx.font='32px sans-serif';ctx.fillText('الحصيلة اليومية',980,145);
  ctx.fillStyle='#183c33';ctx.font='700 44px sans-serif';ctx.fillText(student,980,260);
  ctx.font='30px sans-serif';ctx.fillText(date,980,315);
  const items=[['الحضور',attendanceAr[attendance]||attendance||'—'],['الحفظ الجديد',lesson||'—'],['المراجعة القريبة',recent||'—'],['المراجعة الكبرى',review||'—'],['التقدير',grade||'—'],['ملاحظة',note||'—']];
  let y=400;for(const [k,v] of items){ctx.fillStyle='#D8BD88';ctx.fillRect(80,y-40,920,62);ctx.fillStyle='#183c33';ctx.font='700 30px sans-serif';ctx.fillText(k,960,y);y+=70;ctx.font='28px sans-serif';y=wrapCanvas(ctx,v,960,y,850,44)+34}
  ctx.fillStyle='#00808A';ctx.font='26px sans-serif';ctx.fillText('منصة سنابل الوحي · متابعة تعليمية يومية',980,1280);
  const blob=await new Promise(r=>canvas.toBlob(r,'image/png',0.95));if(!blob)throw Error('تعذر إنشاء بطاقة الحصيلة.');
  const file=new File([blob],`حصيلة-${student}-${date}.png`,{type:'image/png'});
  if(navigator.canShare?.({files:[file]})&&navigator.share){await navigator.share({files:[file],title:'الحصيلة اليومية',text:`حصيلة ${student} - ${date}`});return}
  const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500);
}
const ageFromBirth=d=>{if(!d)return'—';const b=new Date(d+'T00:00:00'),n=new Date;if(Number.isNaN(b.getTime()))return'—';let a=n.getFullYear()-b.getFullYear();const m=n.getMonth()-b.getMonth();if(m<0||(m===0&&n.getDate()<b.getDate()))a--;return a>=0?a:'—'};

const csv=(name,head,data)=>{const cell=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const url=URL.createObjectURL(new Blob(['\ufeff'+[head,...data].map(r=>r.map(cell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
function modal(title){const d=document.createElement('dialog');d.className='sl-dialog';d.innerHTML=`<header><h2>${esc(title)}</h2>${button('إغلاق','close')}</header><div class="sl-body"></div>`;document.body.append(d);d.querySelector('[data-action="close"]').onclick=()=>d.close();d.addEventListener('close',()=>d.remove());d.showModal();return d.querySelector('.sl-body')}
const submit=(form,fn)=>{form.addEventListener('submit',async e=>{e.preventDefault();const b=form.querySelector('[type="submit"]');if(b.disabled)return;b.disabled=true;try{await fn()}catch(e){msg(form,e.message,true)}finally{b.disabled=false}})};
let lookupPromise=null,lookupAt=0;
async function lookups(){if(!lookupPromise||Date.now()-lookupAt>30000){lookupAt=Date.now();lookupPromise=Promise.all([rows('complexes','id,name,org_id',{active:true}),rows('circles','id,name,complex_id,org_id,mosque_id',{active:true}),rows('teachers','id,full_name,circle_id,complex_id,user_id,phone',{active:true})]).then(([complexes,circles,teachers])=>({complexes,circles,teachers})).catch(e=>{lookupPromise=null;throw e})}return lookupPromise}
function bindScope(form,data,initial={}){const cx=form.querySelector('[name="complex_id"]'),ci=form.querySelector('[name="circle_id"]'),te=form.querySelector('[name="teacher_id"]');const opts=(el,items,value)=>{if(!el)return;el.innerHTML='<option value="">اختر</option>'+items.map(x=>`<option value="${esc(x.id)}">${esc(x.name||x.full_name)}</option>`).join('');if(items.some(x=>x.id===value))el.value=value;else if(items.length===1)el.value=items[0].id;};const teachers=()=>opts(te,data.teachers.filter(x=>x.circle_id===ci.value),initial.teacher_id);const circles=()=>{opts(ci,data.circles.filter(x=>x.complex_id===cx.value),initial.circle_id);teachers()};opts(cx,data.complexes,initial.complex_id);cx.onchange=circles;ci.onchange=teachers;circles()}
async function adminCall(action,payload={}){const {data,error}=await sb().functions.invoke('sanabil-user-admin',{body:{action,...payload}});if(error){let m;try{m=(await error.context.json()).error}catch{}throw Error(m||error.message)}return data}
async function usersPanel(root){const [r,l]=await Promise.all([adminCall('list'),lookups()]);root.innerHTML=button('إضافة مستخدم','new')+table(['الاسم','البريد','الدور','حالة الدخول','الإجراءات'],r.users.map((u,i)=>[esc(u.display_name),esc(u.email),esc((u.memberships?.map(m=>roles[m.role]).filter(Boolean).join('، '))||roles[u.role]||'غير مسند'),esc(!u.active?'معطل':!u.email_confirmed?'بانتظار تأكيد البريد':!u.memberships?.some(m=>m.active)?'يحتاج إسناد صلاحية':'جاهز للدخول'),button('تعديل وإسناد',String(i))+(u.active&&!u.email_confirmed?button('تأكيد البريد','confirm-'+i):'')]));const edit=u=>{const body=modal(u?'تعديل حساب وإسناد صلاحياته':'إنشاء حساب دخول');const m=u?.memberships?.[0]||{},multiple=(u?.memberships?.length||0)>1;body.innerHTML=`<form><div class="form-grid two">${field('الاسم الكامل','display_name','text',u?.display_name||'','required')}${u?'':field('البريد الإلكتروني','email','email','','required')}${u?'':field('كلمة المرور المؤقتة','password','password','','required minlength="10" autocomplete="new-password"')}${select('الدور','role',Object.entries(roles).map(([id,name])=>({id,name})),m.role||u?.role||'teacher')}${select('المجمع','complex_id',l.complexes,m.complex_id)}${select('الحلقة (للمعلم)','circle_id',l.circles,m.circle_id)}<label>نشط<input type="checkbox" name="active" ${u?.active===false?'':'checked'}></label></div><button type="submit" class="button button-primary">حفظ الحساب والصلاحيات</button><p>اختيار المجمع والحلقة يحدد البيانات التي يمكن للحساب الوصول إليها.</p></form>`;const f=body.querySelector('form');bindScope(f,l,m);const adapt=()=>{f.elements.role.disabled=multiple;f.elements.complex_id.disabled=multiple||f.elements.role.value==='admin';f.elements.circle_id.disabled=multiple||!['teacher'].includes(f.elements.role.value)};f.elements.role.onchange=adapt;adapt();if(multiple)msg(body,'للحساب إسنادات متعددة؛ سيحافظ الحفظ عليها ويحدّث الاسم والحالة فقط.');submit(f,async()=>{await adminCall(u?'update':'create',{user_id:u?.id,preserve_memberships:multiple,display_name:val(f,'display_name'),email:u?undefined:val(f,'email'),password:u?undefined:val(f,'password'),role:val(f,'role'),complex_id:val(f,'complex_id'),circle_id:val(f,'circle_id'),active:f.elements.active.checked});lookupPromise=null;body.closest('dialog').close();await usersPanel(root);msg(root,'تم حفظ الحساب وصلاحياته.')})};action(root,root.querySelector('[data-action="new"]'),()=>edit(null));r.users.forEach((u,i)=>{action(root,root.querySelector(`[data-action="${i}"]`),()=>edit(u));const cb=root.querySelector(`[data-action="confirm-${i}"]`);if(cb)action(root,cb,async()=>{if(!confirm('تأكيد البريد لهذا الحساب المصرّح له؟'))return;await adminCall('confirm_email',{user_id:u.id});await usersPanel(root)})})}
async function studentsPage(root){const l=await lookups();let page=0,term='',current=[];root.innerHTML=`<div class="sl-toolbar">${field('بحث بالاسم','search')}${button('بحث','search')}${button('إضافة طالب','add')}${button('المعلمون','teachers')}${button('تصدير المعروض','export')}</div><div class="sl-data"></div><div class="sl-toolbar">${button('السابق','prev')}<span class="sl-page"></span>${button('التالي','next')}</div>`;action(root,root.querySelector('[data-action="teachers"]'),()=>{const b=modal('المعلمون المسندون');b.innerHTML=table(['المعلم','الحلقة'],l.teachers.map(t=>[esc(t.full_name),esc(l.circles.find(c=>c.id===t.circle_id)?.name||t.circle_id)]))});const load=async()=>{let q=sb().from('students').select('*').eq('active',true).order('full_name').order('id').range(page*50,page*50+49);if(term)q=q.ilike('full_name','%'+term.replace(/[%_]/g,'')+'%');current=await result(q);root.querySelector('.sl-data').innerHTML=table(['الاسم','العمر','الحلقة','المعلم','ولي الأمر','الإجراءات'],current.map((s,i)=>[esc(s.full_name),esc(ageFromBirth(s.birth_date)),esc(l.circles.find(c=>c.id===s.circle_id)?.name||s.circle_name),esc(l.teachers.find(t=>t.id===s.teacher_id)?.full_name||s.teacher_name),esc(s.guardian_phone),button('تعديل','edit-'+i)+button('إيقاف','off-'+i)]));root.querySelector('.sl-page').textContent='صفحة '+(page+1);root.querySelector('[data-action="prev"]').disabled=page===0;root.querySelector('[data-action="next"]').disabled=current.length<50;current.forEach((s,i)=>{action(root,root.querySelector(`[data-action="edit-${i}"]`),()=>edit(s));action(root,root.querySelector(`[data-action="off-${i}"]`),async()=>{if(!confirm('إيقاف الطالب وإخفاؤه من القوائم اليومية مع حفظ سجلاته؟'))return;await result(sb().from('students').update({active:false}).eq('id',s.id).select('id').single());await load()})})};
const edit=s=>{const b=modal(s?'تعديل بيانات الطالب':'إضافة طالب');b.innerHTML=`<form><div class="form-grid two">${field('الاسم الثلاثي','full_name','text',s?.full_name||'','required')}${field('الهوية أو الإقامة','identity_number','text',s?.identity_number||'')}${field('الجنسية','nationality','text',s?.nationality||'')}${field('الميلاد ميلادي','birth_date','date',s?.birth_date||'')}${field('الميلاد هجري','birth_date_hijri','text',s?.birth_date_hijri||'')}${field('انتهاء الهوية','identity_expiry','date',s?.identity_expiry||'')}${field('المرحلة الدراسية','stage','text',s?.stage||'')}${field('جوال الطالب','student_phone','tel',s?.student_phone||'')}${field('جوال ولي الأمر','guardian_phone','tel',s?.guardian_phone||'')}${select('المجمع','complex_id',l.complexes,s?.complex_id)}${select('الحلقة','circle_id',l.circles,s?.circle_id)}${select('المعلم','teacher_id',l.teachers.map(t=>({id:t.id,name:t.full_name})),s?.teacher_id)}</div><button type="submit" class="button button-primary">حفظ الطالب</button></form>`;const f=b.querySelector('form');bindScope(f,l,s||{});submit(f,async()=>{const row=Object.fromEntries(new FormData(f));if(row.full_name.trim().split(/\s+/).length<3)throw Error('أدخل الاسم الثلاثي');if(!row.circle_id||!row.complex_id)throw Error('اختر المجمع والحلقة');for(const k of ['student_phone','guardian_phone']){row[k]=row[k].replace(/[\s()-]/g,'');if(row[k]&&!/^(?:05\d{8}|(?:\+?966)5\d{8})$/.test(row[k]))throw Error('رقم الجوال غير صحيح: استخدم 05 أو 9665');}for(const k of Object.keys(row))if(row[k]==='')row[k]=null;row.full_name=row.full_name.trim();row.full_name_normalized=row.full_name.replace(/[إأآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ة/g,'ه').replace(/\s+/g,' ');row.org_id=l.circles.find(c=>c.id===row.circle_id).org_id;row.circle_name=l.circles.find(c=>c.id===row.circle_id).name;row.teacher_name=l.teachers.find(t=>t.id===row.teacher_id)?.full_name||null;if(s&&s.circle_id!==row.circle_id)throw Error('نقل الطالب مع حصيلته يحتاج إجراء نقل مخصص؛ لا تغيّر الحلقة من نموذج البيانات.');if(s)await result(sb().from('students').update(row).eq('id',s.id).select('id').single());else await result(sb().from('students').insert({...row,id:crypto.randomUUID(),active:true}).select('id').single());b.closest('dialog').close();await load();msg(root,'حُفظت بيانات الطالب.')})};
action(root,root.querySelector('[data-action="search"]'),async()=>{term=val(root,'search').trim();page=0;await load()});action(root,root.querySelector('[data-action="add"]'),()=>edit(null));action(root,root.querySelector('[data-action="prev"]'),async()=>{page--;await load()});action(root,root.querySelector('[data-action="next"]'),async()=>{page++;await load()});action(root,root.querySelector('[data-action="export"]'),()=>csv('الطلاب',['الاسم','الحلقة','المعلم','جوال ولي الأمر'],current.map(s=>[s.full_name,s.circle_name,s.teacher_name,s.guardian_phone])));await load()}
async function outcomesPage(root){
 const l=await lookups();
 root.innerHTML=`<div class="sl-toolbar">${select('الحلقة','circle',l.circles)}${field('التاريخ','date','date',today())}${button('عرض الطلاب ومقرراتهم','load')}</div><p>يعرض النظام تلقائيًا: الحفظ الجديد، المراجعة القريبة، والمراجعة الكبرى. يسجل المعلم التحضير والتقدير فقط.</p><div class="sl-data"></div>`;
 action(root,root.querySelector('[data-action="load"]'),async()=>{
  const circle=val(root,'circle'),date=val(root,'date');if(!circle||!date)throw Error('اختر الحلقة والتاريخ');
  let students=await rpc('get_daily_assignments',{p_circle_id:circle,p_date:date});
  const box=root.querySelector('.sl-data'),attendanceItems=Object.entries(attendanceAr).map(([id,name])=>({id,name})),gradeItems=['ممتاز','جيد جدًا','جيد','لم يحفظ','لم يسمع'].map(x=>({id:x,name:x}));
  box.innerHTML=`<form><div class="table-wrap"><table><thead><tr><th>الطالب</th><th>التحضير</th><th>الحفظ الجديد</th><th>المراجعة القريبة</th><th>المراجعة الكبرى</th><th>التقدير</th><th>ملاحظة</th><th>مشاركة</th></tr></thead><tbody>${students.length?students.map((s,i)=>`<tr>
   <td><b>${esc(s.fullName)}</b></td>
   <td>${inlineSelect('att'+i,attendanceItems,s.attendanceStatus||'present','حضور '+s.fullName)}</td>
   <td><div class="sl-assignment">${esc(assignmentText(s.memorization))}</div>${s.memorization?button('المصحف','mushaf-m-'+i):''}</td>
   <td><div class="sl-assignment">${esc(assignmentText(s.recentReview))}</div>${s.recentReview?button('المصحف','mushaf-s-'+i):''}</td>
   <td><div class="sl-assignment">${esc(assignmentText(s.review))}</div>${s.review?button('المصحف','mushaf-r-'+i):''}</td>
   <td>${inlineSelect('grade'+i,gradeItems,s.rating||'','تقدير '+s.fullName)}</td>
   <td><input name="note${i}" value="${esc(s.notes||s.attendanceNote||'')}" aria-label="ملاحظة ${esc(s.fullName)}"></td>
   <td>${button('واتساب نص','wa-'+i)}${button('بطاقة صورة','img-'+i)}</td>
  </tr>`).join(''):`<tr><td colspan="8">لا يوجد طلاب نشطون في الحلقة.</td></tr>`}</tbody></table></div><button class="button button-primary" type="submit" ${students.length?'':'disabled'}>حفظ تحضير وحصيلة اليوم</button></form>`;
  const form=box.querySelector('form');
  const currentRow=(s,i)=>{const att=val(form,'att'+i),note=val(form,'note'+i),chosen=val(form,'grade'+i),grade=chosen||(['absent','excused'].includes(att)?'لم يسمع':'');return{att,note,grade,lesson:assignmentText(s.memorization),recent:assignmentText(s.recentReview),review:assignmentText(s.review)}};
  students.forEach((s,i)=>{
   for(const [k,a] of [['m',s.memorization],['s',s.recentReview],['r',s.review]]){const btn=box.querySelector(`[data-action="mushaf-${k}-${i}"]`);if(btn)btn.onclick=()=>openMushaf(a)}
   const bw=box.querySelector(`[data-action="wa-${i}"]`);if(bw)action(box,bw,async()=>{const x=currentRow(s,i);if(!x.grade)throw Error('اختر التقدير قبل المشاركة.');const alert=x.att==='late'?'\nتنبيه: حضر الطالب متأخرًا، ونأمل الحرص على الحضور في الوقت المحدد.':x.att==='absent'?'\nنأمل إفادتنا بسبب غياب الطالب اليوم.':x.att==='excused'?'\nتم تسجيل الطالب مستأذنًا لهذا اليوم.':'';const text=`الحصيلة اليومية - سنابل الوحي\nالطالب: ${s.fullName}\nالتاريخ: ${date}\nالحضور: ${attendanceAr[x.att]||x.att}\nالحفظ الجديد: ${x.lesson}\nالمراجعة القريبة: ${x.recent}\nالمراجعة الكبرى: ${x.review}\nالتقدير: ${x.grade}${x.note?'\nملاحظة: '+x.note:''}${alert}`;window.open(`https://wa.me/${waPhone(s.guardianPhone)}?text=${encodeURIComponent(text)}`,'_blank','noopener,noreferrer')});
   const bi=box.querySelector(`[data-action="img-${i}"]`);if(bi)action(box,bi,async()=>{const x=currentRow(s,i);if(!x.grade)throw Error('اختر التقدير قبل المشاركة.');await shareOutcomeImage(s.fullName,date,x.lesson,x.recent,x.review,x.grade,x.att,x.note)});
  });
  submit(form,async()=>{const payload=students.map((s,i)=>{const x=currentRow(s,i);if(!x.grade)throw Error('اختر تقدير الطالب: '+s.fullName);return{studentId:s.studentId,rating:x.grade,notes:x.note,attendanceStatus:x.att,attendanceNote:x.note}});await rpc('save_daily_outcomes_v2',{p_date:date,p_rows:payload});msg(root,'حُفظ التحضير والحصيلة، وتم ترحيل غير المنجز في كل مسار إلى اليوم التالي.');students=await rpc('get_daily_assignments',{p_circle_id:circle,p_date:date})});
 })
}
async function plansPage(root){
 const students=await rows('students','id,full_name,teacher_id,circle_id',{active:true});
 root.innerHTML=button('خطة جديدة','new')+'<p>يمكن أن تكون للطالب خطة حفظ وخطة مراجعة متزامنتان، ويولد النظام الورد اليومي تلقائيًا.</p><div class="sl-data"></div>';
 const load=async()=>{
  const plans=await rows('plans');plans.sort((a,b)=>String(b.updated_at||'').localeCompare(String(a.updated_at||'')));
  root.querySelector('.sl-data').innerHTML=table(['الطالب','النوع','المقدار','الاتجاه','المدة','الحالة','تفاصيل'],plans.map((p,i)=>[
   esc(students.find(s=>s.id===p.student_id)?.full_name||p.student_id),
   esc(({memorization:'حفظ جديد',recent_review:'مراجعة قريبة',review:'مراجعة كبرى'}[p.type]||p.type)),
   esc(p.daily_amount+' '+({lines:'سطر',pages:'صفحة',ayahs:'آية'}[p.unit]||p.unit)),
   esc(p.direction==='toward_nas'?'نحو الناس':'نحو الفاتحة'),
   esc(p.start_date+' — '+p.end_date),esc(p.status),button('الأيام والاستثناءات','p'+i)
  ]));
  plans.forEach((p,i)=>action(root,root.querySelector(`[data-action="p${i}"]`),async()=>{
   const b=modal('أيام الخطة - '+({memorization:'حفظ جديد',recent_review:'مراجعة قريبة',review:'مراجعة كبرى'}[p.type]||p.type));
   const render=async()=>{
    const days=await rows('plan_days','*',{plan_id:p.id});days.sort((a,b)=>a.date_key.localeCompare(b.date_key));
    b.innerHTML=`<p>يمكن استثناء أي يوم لم يبدأ تنفيذه؛ يعيد النظام جدولة ذلك اليوم وما بعده دون فقد المقرر.</p>`+table(['التاريخ','المقرر','المطلوب','المنجز','المرحل','الحالة','إجراء'],days.map((d,j)=>[
      esc(d.date_key),esc(qref(d.carry_from||d.target_from)+' ← '+qref(d.target_to)),esc(Number(d.target_amount||0)+Number(d.carry_in||0)),esc(d.completed_amount),esc(d.carry_out),esc(d.status),d.rating? 'تم الرصد':button('استثناء اليوم','x'+j)
    ]));
    days.forEach((d,j)=>{const x=b.querySelector(`[data-action="x${j}"]`);if(x)action(b,x,async()=>{if(!confirm('استثناء '+d.date_key+' وإعادة جدولة الأيام التالية؟'))return;const r=await rpc('exclude_plan_date',{p_plan_id:p.id,p_date:d.date_key});msg(b,`تم الاستثناء ونقل ${r.movedDays} يومًا. نهاية الخطة الجديدة: ${r.newEndDate}`);await render();await load()})})
   };await render();
  }))
 };
 action(root,root.querySelector('[data-action="new"]'),async()=>{
  const b=modal('إعداد خطة حفظ أو مراجعة');
  const days=[['0','الأحد'],['1','الاثنين'],['2','الثلاثاء'],['3','الأربعاء'],['4','الخميس'],['5','الجمعة'],['6','السبت']];
  b.innerHTML=`<form><div class="form-grid two">${select('الطالب','student',students.map(s=>({id:s.id,name:s.full_name})))}${select('نوع الخطة','type',[{id:'memorization',name:'حفظ جديد'},{id:'recent_review',name:'مراجعة قريبة / صغرى'},{id:'review',name:'مراجعة كبرى / قديمة'}],'memorization')}${select('الوحدة','unit',[{id:'lines',name:'أسطر'},{id:'pages',name:'صفحات'},{id:'ayahs',name:'آيات'}],'lines')}${field('المقدار اليومي','amount','number','5','min="1" max="45" required')}${select('الاتجاه','direction',[{id:'toward_nas',name:'نحو الناس'},{id:'toward_fatiha',name:'نحو الفاتحة'}],'toward_nas')}${select('سورة البداية','surah',[])}${select('آية البداية','ayah',[])}${field('البداية','start','date',today(),'required')}${field('النهاية المبدئية','end','date','','required')}</div><fieldset><legend>أيام الإجازة الأسبوعية</legend><div class="sl-checks">${days.map(([id,n])=>`<label><input type="checkbox" name="wd${id}" ${['5','6'].includes(id)?'checked':''}> ${n}</label>`).join('')}</div></fieldset><p>بعد الإنشاء تستطيع استثناء تواريخ مفردة من شاشة «الأيام والاستثناءات».</p><button type="submit" class="button button-primary">إنشاء الخطة وتوزيع المقرر</button></form>`;
  const form=b.querySelector('form');await quranFields(form);
  submit(form,async()=>{
   const student=students.find(s=>s.id===val(form,'student'));if(!student)throw Error('اختر الطالب');if(!student.teacher_id)throw Error('يجب إسناد معلم للطالب أولًا');if(val(form,'end')<val(form,'start'))throw Error('النهاية لا تسبق البداية');
   const excluded=days.filter(([id])=>form.querySelector(`[name="wd${id}"]`).checked).map(([id])=>Number(id));
   const r=await rpc('save_plan_with_days',{p_plan_id:crypto.randomUUID(),p_student_id:student.id,p_teacher_id:student.teacher_id,p_program_id:null,p_type:val(form,'type'),p_unit:val(form,'unit'),p_daily_amount:Number(val(form,'amount')),p_direction:val(form,'direction'),p_start_surah:Number(val(form,'surah')),p_start_ayah:Number(val(form,'ayah')),p_start_date:val(form,'start'),p_end_date:val(form,'end'),p_excluded_weekdays:excluded,p_status:'active',p_replace_existing:false});
   b.closest('dialog').close();await load();msg(root,`حُفظت الخطة ووزّع النظام المقرر على ${r.generatedDays} يومًا${r.boundaryReached?' حتى نهاية نطاق القرآن':''}.`);
  })
 });await load()
}
async function attendancePage(root){
 const a=await access(),l=await lookups(),manager=a.roles.some(r=>['admin','manager','supervisor'].includes(r)),teacher=a.roles.includes('teacher');
 root.innerHTML=`<div class="sl-toolbar">${select('الحلقة','circle',l.circles)}${field('التاريخ','date','date',today())}${teacher?button('تسجيل حضوري','in')+button('تسجيل انصرافي','out'):''}${manager?button('إعدادات بصمة الحلقة','fingerprint-settings')+button('اعتماد الغائبين','mark-absent'):''}${button('تحديث','load')}</div><div class="sl-window"></div><div class="sl-data"></div>`;
 const selected=()=>l.circles.find(c=>c.id===val(root,'circle'));
 const getWindow=async c=>{if(!c?.mosque_id)return null;const {data,error}=await sb().functions.invoke('sanabil-attendance',{body:{action:'window',mosqueId:c.mosque_id,circleId:c.id}});if(error)throw Error(error.message);if(data?.error)throw Error(data.error);return data.window};
 const minuteNow=()=>{const p=new Intl.DateTimeFormat('en-GB',{timeZone:'Asia/Riyadh',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(new Date),get=t=>p.find(x=>x.type===t)?.value||'0';return Number(get('hour'))*60+Number(get('minute'))};
 const tmin=x=>{const [h,m]=String(x||'00:00').split(':').map(Number);return h*60+m};
 let lastWindow=null,lastAttendance=[];
 const load=async()=>{
  const c=selected(),date=val(root,'date');if(!c||!date){root.querySelector('.sl-data').innerHTML='<p>اختر الحلقة والتاريخ.</p>';return}
  const [att,win]=await Promise.all([rows('attendance','*',{circle_id:c.id,date_key:date}),getWindow(c)]);lastWindow=win;lastAttendance=att;
  root.querySelector('.sl-window').innerHTML=win?`<p><b>نافذة اليوم:</b> ${esc(win.start)} – ${esc(win.end)} · السماح بالتأخير ${esc(win.lateAllowMinutes)} د · الحضور المبكر ${esc(win.earlyArrivalMinutes)} د · الانصراف المبكر ${esc(win.earlyLeaveMinutes)} د · الغياب بعد ${esc(win.absenceAfterMinutes)} د · النطاق ${esc(win.radiusMeters)}م.</p>`:'';
  const teachers=l.teachers.filter(t=>t.circle_id===c.id),day=new Date(date+'T12:00:00+03:00').getDay(),working=win?.weekdays?.map(Number).includes(day);
  const autoAbsent=working&&(date<today()||(date===today()&&minuteNow()>tmin(win.start)+Number(win.absenceAfterMinutes||60)));
  root.querySelector('.sl-data').innerHTML=table(['المعلم','الحضور','الانصراف','الحالة','ملاحظة','إجراء'],teachers.map((t,i)=>{
    const r=att.find(x=>x.teacher_id===t.id),bits=[];
    if(r?.status==='excused')bits.push('مستأذن');else if(r?.status==='absent')bits.push('غائب');
    else if(r?.check_in_at){bits.push('حاضر');if(Number(r.late_minutes)>0)bits.push('متأخر '+r.late_minutes+' د');if(Number(r.early_arrival_minutes)>0)bits.push('مبكر '+r.early_arrival_minutes+' د');if(Number(r.early_leave_minutes)>0)bits.push('انصرف مبكرًا '+r.early_leave_minutes+' د')}
    else bits.push(autoAbsent?'غائب - غير معتمد':'لم يسجل');
    const noteworthy=r?.status==='excused'||r?.status==='absent'||Number(r?.late_minutes)>0||autoAbsent;
    return[esc(t.full_name),esc(dateText(r?.check_in_at)),esc(dateText(r?.check_out_at)),esc(bits.join(' · ')),esc(r?.excuse_note||'—'),(manager&&!r?.check_in_at?button('مستأذن','exc-'+i)+button('غائب','abs-'+i):'')+(manager&&noteworthy&&t.phone?button('مراسلة','msg-'+i):'')];
  }));
  if(manager)teachers.forEach((t,i)=>{
   const r=att.find(x=>x.teacher_id===t.id);
   for(const [kind,status] of [['exc','excused'],['abs','absent']]){const btn=root.querySelector(`[data-action="${kind}-${i}"]`);if(btn)action(root,btn,async()=>{const note=prompt(status==='excused'?'سبب الاستئذان:':'سبب الغياب أو الملاحظة:','')||'';await rpc('set_teacher_attendance_override',{p_teacher_id:t.id,p_date:date,p_status:status,p_note:note});await load()})}
   const mb=root.querySelector(`[data-action="msg-${i}"]`);if(mb)action(root,mb,async()=>{const state=r?.status==='excused'?'الاستئذان':r?.status==='absent'?'الغياب':Number(r?.late_minutes)>0?'التأخر في الحضور':'عدم تسجيل الحضور';const txt=`السلام عليكم ورحمة الله وبركاته، نود الاستفسار عن ${state} بتاريخ ${date}. شاكرين تعاونكم. — سنابل الوحي`;window.open(`https://wa.me/${waPhone(t.phone)}?text=${encodeURIComponent(txt)}`,'_blank','noopener,noreferrer')})
  })
 };
 for(const kind of ['in','out']){const btn=root.querySelector(`[data-action="${kind}"]`);if(btn)action(root,btn,async()=>{const c=selected();if(!c?.mosque_id)throw Error('اختر حلقة مرتبطة بمسجد');if(val(root,'date')!==today())throw Error('البصمة الجغرافية متاحة لليوم الحالي فقط');const p=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,e=>reject(Error(e.code===1?'اسمح بالوصول للموقع لتسجيل البصمة.':'تعذر تحديد الموقع؛ أعد المحاولة.')),{enableHighAccuracy:true,timeout:20000,maximumAge:0}));const {data,error}=await sb().functions.invoke('sanabil-attendance',{body:{action:kind==='in'?'checkIn':'checkOut',mosqueId:c.mosque_id,circleId:c.id,latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}});if(error){let t=error.message;try{t=(await error.context.json()).error||t}catch{}throw Error(t)}if(data?.error)throw Error(data.error);await load();const extra=kind==='in'&&data.lateMinutes>0?' (متأخر '+data.lateMinutes+' دقيقة)':kind==='in'&&data.earlyArrivalMinutes>0?' (حضور مبكر '+data.earlyArrivalMinutes+' دقيقة)':'';msg(root,(kind==='in'?'تم تسجيل الحضور':'تم تسجيل الانصراف')+extra)})}
 if(manager){
  action(root,root.querySelector('[data-action="mark-absent"]'),async()=>{const c=selected(),date=val(root,'date');if(!c)throw Error('اختر الحلقة');if(!lastWindow)await load();const day=new Date(date+'T12:00:00+03:00').getDay(),working=lastWindow?.weekdays?.map(Number).includes(day);if(!working)throw Error('هذا اليوم مستبعد من أيام الدوام.');const due=date<today()||(date===today()&&minuteNow()>tmin(lastWindow.start)+Number(lastWindow.absenceAfterMinutes||60));if(!due)throw Error('لم يحن وقت اعتماد الغياب بعد.');const teachers=l.teachers.filter(t=>t.circle_id===c.id),missing=teachers.filter(t=>!lastAttendance.some(r=>r.teacher_id===t.id));if(!missing.length)throw Error('لا يوجد معلمون بلا سجل حضور.');if(!confirm('اعتماد '+missing.length+' معلم/معلمين غائبين؟'))return;for(const t of missing)await rpc('set_teacher_attendance_override',{p_teacher_id:t.id,p_date:date,p_status:'absent',p_note:'غياب لعدم تسجيل الحضور بعد الوقت المحدد'});await load();msg(root,'تم اعتماد حالات الغياب.')});
  action(root,root.querySelector('[data-action="fingerprint-settings"]'),async()=>{const c=selected();if(!c?.mosque_id)throw Error('اختر حلقة مرتبطة بمسجد');const m=await result(sb().from('mosques').select('*').eq('id',c.mosque_id).single()),cfg=Array.isArray(m.attendance_windows)?m.attendance_windows[0]||{}:{},d=modal('إعدادات بصمة '+m.name),prayers=[{id:'Fajr',name:'الفجر'},{id:'Dhuhr',name:'الظهر'},{id:'Asr',name:'العصر'},{id:'Maghrib',name:'المغرب'},{id:'Isha',name:'العشاء'}];d.innerHTML=`<form><div class="form-grid two">${field('خط العرض','latitude','number',m.latitude,'step="any" required')}${field('خط الطول','longitude','number',m.longitude,'step="any" required')}${field('النطاق بالمتر','radius','number',m.radius_meters||100,'min="20" max="500"')}${select('البداية','startPrayer',prayers,cfg.startPrayer||'Asr')}${select('النهاية','endPrayer',prayers,cfg.endPrayer||'Maghrib')}${field('سماح التأخير','late','number',cfg.lateAllowMinutes??15,'min="0" max="180"')}${field('الحضور المبكر','early','number',cfg.earlyArrivalMinutes??15,'min="0" max="180"')}${field('الانصراف المبكر','leave','number',cfg.earlyLeaveMinutes??15,'min="0" max="180"')}${field('اعتبار الغياب بعد','absent','number',cfg.absenceAfterMinutes??60,'min="0" max="360"')}</div><button type="button" class="button button-soft" data-action="gps">استخدام موقعي</button><button type="submit" class="button button-primary">حفظ</button></form>`;const form=d.querySelector('form');action(d,d.querySelector('[data-action="gps"]'),async()=>{const p=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000}));form.elements.latitude.value=p.coords.latitude;form.elements.longitude.value=p.coords.longitude});submit(form,async()=>{const config={...cfg,action:'both',weekdays:cfg.weekdays||['0','1','2','3','4'],start:'00:00',end:'23:59',startPrayer:val(form,'startPrayer'),endPrayer:val(form,'endPrayer'),lateAllowMinutes:Number(val(form,'late')),earlyArrivalMinutes:Number(val(form,'early')),earlyLeaveMinutes:Number(val(form,'leave')),absenceAfterMinutes:Number(val(form,'absent')),checkoutGraceMinutes:Number(cfg.checkoutGraceMinutes??120)};await result(sb().from('mosques').update({latitude:Number(val(form,'latitude')),longitude:Number(val(form,'longitude')),radius_meters:Number(val(form,'radius')),attendance_windows:[config],updated_at:new Date().toISOString()}).eq('id',m.id).select('id').single());d.closest('dialog').close();await load();msg(root,'تم حفظ إعدادات البصمة لهذا المجمع.')})})
 }
 action(root,root.querySelector('[data-action="load"]'),load);await load()
}

async function requestPanel(root,options={}){
 const a=await access(),canSchedule=options.canSchedule??a.roles.some(r=>['admin','manager','supervisor'].includes(r));
 const students=await rows('students','id,full_name,org_id,complex_id,circle_id,teacher_id,teacher_name',{active:true});
 const examiners=options.examiners??(canSchedule?await rows('examiners','id,full_name,complex_id',{active:true}):[]);
 root.innerHTML=`<form><div class="form-grid two">${select('الطالب','student',students.map(x=>({id:x.id,name:x.full_name})))}${select('النوع','type',[{id:'custom',name:'مخصص'},{id:'full',name:'كامل القرآن'}],'custom')}${field('المقرر المطلوب','syllabus','text','','required')}${field('عدد الأسئلة','count','number',3,'min="2" max="15" required')}${field('أسطر السؤال','lines','number',10,'min="5" max="15" required')}</div><button type="submit" class="button button-primary">إرسال طلب الاختبار</button></form><div class="sl-requests"></div>`;
 const scheduleRequest=async req=>{
  const s=students.find(x=>x.id===req.student_id);if(!s)throw Error('بيانات الطالب غير متاحة.');
  const m=modal('جدولة طلب اختبار - '+s.full_name);
  m.innerHTML=`<form><p><b>المقرر:</b> ${esc(req.syllabus?.label||req.type)} · <b>الأسئلة:</b> ${esc(req.question_count)}</p><div class="form-grid two">${select('المختبر (اختياري إذا سيجريه المشرف)','examiner',examiners.map(x=>({id:x.id,name:x.full_name})))}${field('الموعد بتوقيت السعودية','when','datetime-local','','required')}</div><button type="submit" class="button button-primary">اعتماد الموعد</button></form>`;
  const form=m.querySelector('form');
  submit(form,async()=>{
   const ex=examiners.find(x=>x.id===val(form,'examiner'));if(ex&&ex.complex_id!==s.complex_id)throw Error('المختبر لا يتبع مجمع الطالب.');
   const scheduleId=crypto.randomUUID();
   await result(sb().from('exam_schedules').insert({
    id:scheduleId,request_id:req.id,student_id:s.id,student_name:s.full_name,
    teacher_id:s.teacher_id,teacher_name:s.teacher_name,org_id:s.org_id,complex_id:s.complex_id,circle_id:s.circle_id,
    assigned_examiner_id:ex?.id||null,type:req.type,syllabus_label:req.syllabus?.label||req.type,
    syllabus:{...(req.syllabus||{}),questionCount:req.question_count,linesPerQuestion:req.lines_per_question},
    scheduled_at:new Date(val(form,'when')+':00+03:00').toISOString(),status:'scheduled'
   }).select('id').single());
   await result(sb().from('exam_requests').update({status:'scheduled',updated_at:new Date().toISOString()}).eq('id',req.id).select('id').single());
   m.closest('dialog').close();await refresh();await options.onScheduled?.();msg(root,'تمت جدولة الطلب وربطه بالموعد.');
  })
 };
 const refresh=async()=>{
  const list=await rows('exam_requests');list.sort((x,y)=>String(y.requested_at).localeCompare(String(x.requested_at)));
  root.querySelector('.sl-requests').innerHTML=table(['الطالب','المقرر','الأسئلة','تاريخ الطلب','الحالة','إجراء'],list.map((r,i)=>[
   esc(students.find(s=>s.id===r.student_id)?.full_name||r.student_id),esc(r.syllabus?.label||r.type),esc(r.question_count),
   esc(dateText(r.requested_at)),esc({pending:'قيد المراجعة',approved:'مقبول',scheduled:'مجدول',rejected:'مرفوض',cancelled:'ملغي'}[r.status]||r.status),
   canSchedule&&['pending','approved'].includes(r.status)?button('جدولة','schedule-'+i):'—'
  ]));
  if(canSchedule)list.forEach((r,i)=>{const btn=root.querySelector(`[data-action="schedule-${i}"]`);if(btn)action(root,btn,()=>scheduleRequest(r))})
 };
 const form=root.querySelector('form');
 submit(form,async()=>{
  const s=students.find(s=>s.id===val(form,'student'));if(!s)throw Error('اختر الطالب');if(!s.teacher_id)throw Error('الطالب غير مسند إلى معلم.');
  await result(sb().from('exam_requests').insert({
   id:crypto.randomUUID(),org_id:s.org_id,complex_id:s.complex_id,circle_id:s.circle_id,teacher_id:s.teacher_id,student_id:s.id,
   type:val(form,'type'),syllabus:{label:val(form,'syllabus')},question_count:Number(val(form,'count')),lines_per_question:Number(val(form,'lines')),status:'pending'
  }).select('id').single());
  form.reset();await refresh();msg(root,'تم تسجيل طلب الاختبار وسيظهر للمشرف مباشرة.');
 });
 await refresh()
}
async function testsPage(root){
 const a=await access(),manage=a.roles.some(r=>['admin','manager','supervisor','examiner'].includes(r)),canSchedule=a.roles.some(r=>['admin','manager','supervisor'].includes(r));
 const [students,examiners]=await Promise.all([
  rows('students','id,full_name,teacher_id,teacher_name,circle_id,complex_id,org_id,guardian_phone',{active:true}),
  manage?rows('examiners','id,full_name,complex_id',{active:true}):Promise.resolve([])
 ]);
 root.innerHTML=button('طلبات الاختبار','requests')+(canSchedule?button('جدولة مباشرة','new'):'')+'<div class="sl-data"></div>';
 action(root,root.querySelector('[data-action="requests"]'),async()=>{const m=modal('طلبات الاختبار');await requestPanel(m,{canSchedule,examiners,onScheduled:load})});
 const load=async()=>{
  const data=await rows('exam_schedules');data.sort((x,y)=>String(y.scheduled_at).localeCompare(String(x.scheduled_at)));
  root.querySelector('.sl-data').innerHTML=table(['الطالب','الموعد','المقرر','الحالة','النتيجة','إجراء'],data.map((d,i)=>[
   esc(d.student_name),esc(dateText(d.scheduled_at)),esc(d.syllabus_label),
   esc({scheduled:'مجدول',confirmed:'مؤكد',in_progress:'جارٍ',completed:'مكتمل',postponed:'مؤجل',no_show:'لم يحضر',cancelled:'ملغي'}[d.status]||d.status),
   esc(d.scores?.total??'—'),
   (manage&&['scheduled','confirmed','in_progress'].includes(d.status)?button('فتح الاختبار','t'+i):'')+(d.status==='completed'&&d.scores?button('مشاركة النتيجة','share-'+i):'—')
  ]));
  data.forEach((d,i)=>{
   const open=root.querySelector(`[data-action="t${i}"]`);if(open)action(root,open,async()=>{await rpc('start_exam',{p_schedule_id:d.id});await exam(d);await load()});
   const share=root.querySelector(`[data-action="share-${i}"]`);if(share)action(root,share,async()=>{
    const s=students.find(x=>x.id===d.student_id),txt=`نتيجة اختبار القرآن — سنابل الوحي\nالطالب: ${d.student_name}\nالمقرر: ${d.syllabus_label||''}\nالحفظ: ${d.scores?.memorization??'—'} / 80\nالتجويد: ${d.scores?.tajweed??'—'} / 20\nالمجموع: ${d.scores?.total??'—'} / 100`;
    window.open(`https://wa.me/${waPhone(s?.guardian_phone)}?text=${encodeURIComponent(txt)}`,'_blank','noopener,noreferrer')
   })
  })
 };
 const exam=async d=>{
  const m=modal('رصد الاختبار: '+d.student_name);
  const request=d.request_id?await result(sb().from('exam_requests').select('question_count').eq('id',d.request_id).single()):null;
  const count=Number(request?.question_count||d.syllabus?.questionCount||3);
  m.innerHTML=`<form><p>خصم الخطأ: درجتان، الشك: درجة، التجويد: ربع درجة لكل سؤال. تُحسب النتيجة النهائية في الخادم.</p><div class="sl-questions"></div>${field('ملحوظات','notes')}<button type="submit" class="button button-primary">حفظ النتيجة النهائية</button></form>`;
  const form=m.querySelector('form'),boxes=[];
  for(let i=0;i<count;i++){const q=document.createElement('fieldset');q.innerHTML=`<legend>السؤال ${i+1}</legend><div class="form-grid three">${select('السورة','surah',[])}${select('الآية','ayah',[])}${field('الأخطاء','errors','number',0,'min="0" max="100" required')}${field('الشكوك','doubts','number',0,'min="0" max="100" required')}${field('أخطاء التجويد','tajweed','number',0,'min="0" max="100" required')}</div>`;form.querySelector('.sl-questions').append(q);boxes.push(q);await quranFields(q)}
  submit(form,async()=>{const r=await rpc('complete_exam',{p_schedule_id:d.id,p_answers:boxes.map(q=>({surahNo:Number(val(q,'surah')),ayahNo:Number(val(q,'ayah')),errors:Number(val(q,'errors')),doubts:Number(val(q,'doubts')),tajweed:Number(val(q,'tajweed'))})),p_notes:val(form,'notes')});m.innerHTML=`<h3>حُفظت النتيجة</h3><p>الحفظ: ${esc(r.scores.memorization)} / 80 — التجويد: ${esc(r.scores.tajweed)} / 20 — المجموع: ${esc(r.scores.total)} / 100</p><p>رمز الاستعلام: ${esc(r.publicCode||'—')}</p>`;await load()})
 };
 if(canSchedule)action(root,root.querySelector('[data-action="new"]'),()=>{
  const m=modal('جدولة اختبار مباشرة');
  m.innerHTML=`<form><div class="form-grid two">${select('الطالب','student',students.map(s=>({id:s.id,name:s.full_name})))}${select('المختبر (اختياري إذا سيجريه المشرف)','examiner',examiners.map(s=>({id:s.id,name:s.full_name})))}${field('الموعد بتوقيت السعودية','when','datetime-local','','required')}${select('نوع الاختبار','type',[{id:'custom',name:'مخصص'},{id:'full',name:'كامل القرآن'}],'custom')}${field('المقرر','syllabus','text','','required')}${field('عدد الأسئلة','count','number',3,'min="2" max="15" required')}</div><button type="submit" class="button button-primary">حفظ الموعد</button></form>`;
  const form=m.querySelector('form');
  submit(form,async()=>{
   const s=students.find(x=>x.id===val(form,'student')),ex=examiners.find(x=>x.id===val(form,'examiner'));if(!s)throw Error('اختر الطالب');if(ex&&ex.complex_id!==s.complex_id)throw Error('المختبر لا يتبع مجمع الطالب.');
   await result(sb().from('exam_schedules').insert({
    id:crypto.randomUUID(),student_id:s.id,student_name:s.full_name,teacher_id:s.teacher_id,teacher_name:s.teacher_name,
    org_id:s.org_id,complex_id:s.complex_id,circle_id:s.circle_id,assigned_examiner_id:ex?.id||null,type:val(form,'type'),
    syllabus_label:val(form,'syllabus'),syllabus:{questionCount:Number(val(form,'count'))},
    scheduled_at:new Date(val(form,'when')+':00+03:00').toISOString(),status:'scheduled'
   }).select('id').single());
   m.closest('dialog').close();await load();msg(root,'حُفظ موعد الاختبار، ويمكن للمشرف إجراء الاختبار مباشرة أو إسناده لمختبر.');
  })
 });
 await load()
}
const reportTables={outcomes:{name:'الحصيلة',date:'date_key',head:['التاريخ','الطالب','الحفظ','المراجعة القريبة','المراجعة الكبرى','التقدير'],map:(r,n)=>[r.date_key,n[r.student_id]||r.student_id,r.new_lesson,r.recent_review,r.review,r.rating]},tests:{name:'الاختبارات',date:'performed_at',head:['التاريخ','الطالب','الحفظ','التجويد','المجموع'],map:r=>[dateText(r.performed_at),r.student_name_snapshot,r.scores?.memorization,r.scores?.tajweed,r.scores?.total]},attendance:{name:'حضور المعلمين',date:'date_key',head:['التاريخ','المعلم','الحضور','الانصراف','التأخر','الحضور المبكر','الانصراف المبكر','الحالة'],map:(r,n,t)=>[r.date_key,t[r.teacher_id]||r.teacher_id,dateText(r.check_in_at),dateText(r.check_out_at),r.late_minutes||0,r.early_arrival_minutes||0,r.early_leave_minutes||0,r.status]},student_attendance:{name:'حضور الطلاب',date:'date_key',head:['التاريخ','الطالب','الحالة','الملاحظة'],map:(r,n)=>[r.date_key,n[r.student_id]||r.student_id,attendanceAr[r.status]||r.status,r.note||'']},plans:{name:'الخطط',date:'start_date',head:['الطالب','النوع','البداية','النهاية','المقدار','الحالة'],map:(r,n)=>[n[r.student_id]||r.student_id,r.type==='review'?'مراجعة':'حفظ',r.start_date,r.end_date,r.daily_amount,r.status]}};
async function reportPage(root){const l=await lookups();root.innerHTML=`<div class="sl-toolbar">${select('السجل','kind',Object.entries(reportTables).map(([id,x])=>({id,name:x.name})),'outcomes')}${select('الحلقة','circle',l.circles,'','جميع الحلقات')}${field('من','from','date',today().slice(0,7)+'-01')}${field('إلى','to','date',today())}${field('اسم الطالب','search')}${button('عرض النتائج','load')}${button('تصدير CSV','csv')}${button('طباعة / PDF','print')}</div><div class="sl-data"></div>`;let exported=null;action(root,root.querySelector('[data-action="load"]'),async()=>{exported=null;const kind=val(root,'kind'),cfg=reportTables[kind],from=val(root,'from'),to=val(root,'to');if(!cfg||!from||!to||from>to)throw Error('تحقق من الفترة؛ تاريخ النهاية لا يسبق البداية.');let data=[];for(let offset=0;;offset+=500){let q=sb().from(kind).select('*').gte(cfg.date,kind==='tests'?from+'T00:00:00+03:00':from).lte(cfg.date,kind==='tests'?to+'T23:59:59.999+03:00':to).order(cfg.date).order('id').range(offset,offset+499);if(val(root,'circle'))q=q.eq('circle_id',val(root,'circle'));const part=await result(q);data.push(...part);if(part.length<500)break;}const ids=[...new Set(data.map(r=>r.student_id).filter(Boolean))];let students=[];for(let i=0;i<ids.length;i+=100)students.push(...await result(sb().from('students').select('id,full_name').in('id',ids.slice(i,i+100))));const names=Object.fromEntries(students.map(s=>[s.id,s.full_name])),teachers=Object.fromEntries(l.teachers.map(t=>[t.id,t.full_name]));const term=val(root,'search').trim();if(term)data=data.filter(r=>String(names[r.student_id]||r.student_name_snapshot||'').includes(term));const mapped=data.map(r=>cfg.map(r,names,teachers));exported={head:cfg.head,data:mapped,title:cfg.name};root.querySelector('.sl-data').innerHTML=`<p>عدد السجلات: ${mapped.length} — من ${esc(from)} إلى ${esc(to)}</p>`+table(cfg.head,mapped.map(r=>r.map(esc)))});action(root,root.querySelector('[data-action="csv"]'),()=>{if(!exported)throw Error('اعرض النتائج أولًا');csv(exported.title,exported.head,exported.data)});action(root,root.querySelector('[data-action="print"]'),()=>{if(!exported)throw Error('اعرض النتائج أولًا');window.print()})}
async function statisticsPage(root){
 const l=await lookups();
 root.innerHTML=`<div class="sl-toolbar">${select('الحلقة','circle',l.circles,'','جميع الحلقات')}${field('من','from','date',today().slice(0,7)+'-01')}${field('إلى','to','date',today())}${button('تحديث المؤشرات','load')}${button('التقارير التفصيلية','detail')}${button('تصدير الملخص','csv')}</div><div class="sl-stats"></div>`;
 let exported=null;
 const rangeRows=async(table,dateCol,from,to,circle)=>{let all=[];for(let offset=0;;offset+=500){let q=sb().from(table).select('*').gte(dateCol,from).lte(dateCol,to).order(dateCol).range(offset,offset+499);if(circle)q=q.eq('circle_id',circle);const part=await result(q);all.push(...part);if(part.length<500)return all}};
 const load=async()=>{
  const from=val(root,'from'),to=val(root,'to'),circle=val(root,'circle');if(!from||!to||from>to)throw Error('تحقق من الفترة المحددة.');
  let sq=sb().from('students').select('*').eq('active',true),tq=sb().from('teachers').select('*').eq('active',true);if(circle){sq=sq.eq('circle_id',circle);tq=tq.eq('circle_id',circle)}
  const [students,teachers,sa,outcomes,ta,tests,days]=await Promise.all([
   result(sq),result(tq),rangeRows('student_attendance','date_key',from,to,circle),rangeRows('outcomes','date_key',from,to,circle),rangeRows('attendance','date_key',from,to,circle),rangeRows('tests','performed_at',from+'T00:00:00+03:00',to+'T23:59:59.999+03:00',circle),rangeRows('plan_days','date_key',from,to,circle)
  ]);
  const attended=sa.filter(x=>['present','late'].includes(x.status)).length,studentRate=sa.length?Math.round(attended/sa.length*100):0;
  const done=outcomes.filter(x=>['ممتاز','جيد جدًا','جيد'].includes(x.rating)).length,outcomeRate=outcomes.length?Math.round(done/outcomes.length*100):0;
  const testScores=tests.map(x=>Number(x.scores?.total)).filter(Number.isFinite),testAvg=testScores.length?Math.round(testScores.reduce((a,b)=>a+b,0)/testScores.length*10)/10:0;
  const due=days.filter(x=>x.date_key<=to),completed=due.filter(x=>x.status==='completed').length,planRate=due.length?Math.round(completed/due.length*100):0;
  const teacherLate=ta.filter(x=>Number(x.late_minutes)>0).length,teacherExcused=ta.filter(x=>x.status==='excused').length,teacherAbsent=ta.filter(x=>x.status==='absent').length;
  const cards=[['الطلاب النشطون',students.length],['المعلمون النشطون',teachers.length],['حضور الطلاب',studentRate+'%'],['إنجاز الحصيلة',outcomeRate+'%'],['إنجاز أيام الخطط',planRate+'%'],['متوسط الاختبارات',testAvg],['تأخر المعلمين',teacherLate],['استئذان/غياب المعلمين',teacherExcused+' / '+teacherAbsent]];
  const circles=(circle?l.circles.filter(x=>x.id===circle):l.circles).map(cx=>{
   const ss=students.filter(x=>x.circle_id===cx.id),aa=sa.filter(x=>x.circle_id===cx.id),oo=outcomes.filter(x=>x.circle_id===cx.id),dd=days.filter(x=>x.circle_id===cx.id&&x.date_key<=to),tt=tests.filter(x=>x.circle_id===cx.id);
   const ar=aa.length?Math.round(aa.filter(x=>['present','late'].includes(x.status)).length/aa.length*100):0,or=oo.length?Math.round(oo.filter(x=>['ممتاز','جيد جدًا','جيد'].includes(x.rating)).length/oo.length*100):0,pr=dd.length?Math.round(dd.filter(x=>x.status==='completed').length/dd.length*100):0,ts=tt.map(x=>Number(x.scores?.total)).filter(Number.isFinite),avg=ts.length?Math.round(ts.reduce((a,b)=>a+b,0)/ts.length*10)/10:0;
   return[cx.name,ss.length,ar+'%',or+'%',pr+'%',avg]
  });
  exported={head:['الحلقة','الطلاب','الحضور','إنجاز الحصيلة','إنجاز الخطط','متوسط الاختبارات'],data:circles,title:'إحصاءات سنابل الوحي'};
  root.querySelector('.sl-stats').innerHTML=`<div class="stats-grid">${cards.map(([k,v])=>`<article class="stat-card"><span>${esc(k)}</span><b>${esc(v)}</b></article>`).join('')}</div><h2>مقارنة الحلقات</h2>${table(exported.head,circles.map(r=>r.map(esc)))}<p>الفترة: ${esc(from)} إلى ${esc(to)}. المؤشرات مبنية على السجلات الفعلية ضمن صلاحيات الحساب.</p>`;
 };
 action(root,root.querySelector('[data-action="load"]'),load);
 action(root,root.querySelector('[data-action="detail"]'),async()=>{const b=modal('التقارير التفصيلية');await reportPage(b)});
 action(root,root.querySelector('[data-action="csv"]'),()=>{if(!exported)throw Error('حدّث المؤشرات أولًا');csv(exported.title,exported.head,exported.data)});
 await load()
}
async function dashboard(root){const a=await access();const queries=[['الطلاب النشطون','students',{active:true}],['المعلمون النشطون','teachers',{active:true}],['الحضور اليوم','attendance',{date_key:today()}],['الحصائل اليوم','outcomes',{date_key:today()}]];const counts=await Promise.all(queries.map(async([title,t,f])=>{let q=sb().from(t).select('id',{count:'exact',head:true});for(const [k,v]of Object.entries(f))q=q.eq(k,v);const r=await q;if(r.error)throw Error(r.error.message);return{title,count:r.count}}));root.innerHTML=`<h2>أهلًا ${esc(a.profile?.display_name||'بك')}</h2><p>${esc(today())} — بيانات ضمن نطاق صلاحياتك</p>${a.requires_scope_assignment?'<p role="alert">حسابك نشط، لكنه يحتاج ربطًا بالمجمع والحلقة من إدارة المستخدمين حتى تظهر السجلات.</p>':''}<div class="stats-grid">${counts.map(c=>`<article class="stat-card"><span>${esc(c.title)}</span><b>${c.count}</b></article>`).join('')}</div><p>آخر تحديث: ${esc(new Date().toLocaleTimeString('ar-SA',{timeZone:'Asia/Riyadh'}))}</p>`;if(a.roles.includes('admin')){root.insertAdjacentHTML('beforeend',button('إدارة المستخدمين','users'));action(root,root.querySelector('[data-action="users"]'),async()=>{const b=modal('الحسابات والصلاحيات');await usersPanel(b)})}}
async function settingsPage(root){
 const a=await access();if(!a.roles.includes('admin'))throw Error('هذه الصفحة لمدير النظام');
 root.innerHTML=`<div class="sl-toolbar">${button('إدارة المستخدمين','users')}${button('إضافة مجمع','add-complex')}${button('إضافة مسجد وموقع بصمة','add-mosque')}${button('إضافة حلقة','add-circle')}</div><div class="sl-settings"></div><div class="sl-structure"></div>`;
 action(root,root.querySelector('[data-action="users"]'),async()=>{const b=modal('الحسابات والصلاحيات');await usersPanel(b)});
 const load=async()=>{
  const [items,complexes,mosques,circles]=await Promise.all([rows('settings','*',{org_id:a.org_id}),rows('complexes','*'),rows('mosques','*'),rows('circles','*')]);
  const s=items.find(x=>x.id===a.org_id+'_settings'),v=s?.values||{},box=root.querySelector('.sl-settings');
  box.innerHTML=`<h2>إعدادات عامة</h2><form><div class="form-grid two">${field('اسم المنصة','platformName','text',v.platformName||'سنابل الوحي')}${field('أيام السماح بتعديل الحصيلة','outcomesEditDays','number',v.outcomesEditDays??7,'min="0" max="365" required')}</div><button type="submit" class="button button-primary">حفظ الإعدادات العامة</button></form>`;
  submit(box.querySelector('form'),async()=>{const values={...v,platformName:val(box,'platformName'),outcomesEditDays:Number(val(box,'outcomesEditDays')),timezone:'Asia/Riyadh'};await result(sb().from('settings').upsert({id:s?.id||a.org_id+'_settings',org_id:a.org_id,values}).select('id').single());msg(box,'تم حفظ الإعدادات العامة.')});
  const area=root.querySelector('.sl-structure');
  area.innerHTML=`<h2>المجمعات</h2>${table(['المجمع','الحالة'],complexes.map(x=>[esc(x.name),esc(x.active?'نشط':'موقف')]))}<h2>المساجد ومواقع البصمة</h2>${table(['المسجد','المجمع','الإحداثيات','النطاق','إعدادات الحضور','إجراء'],mosques.map((m,i)=>{const cfg=Array.isArray(m.attendance_windows)?m.attendance_windows[0]||{}:{};return[esc(m.name),esc(complexes.find(x=>x.id===m.complex_id)?.name||m.complex_id),esc(m.latitude+', '+m.longitude),esc(m.radius_meters+'م'),esc((cfg.startPrayer||'Asr')+' → '+(cfg.endPrayer||'Maghrib')+' · تأخير '+(cfg.lateAllowMinutes??15)+'د'),button('تعديل','mosque-'+i)]}))}<h2>الحلقات</h2>${table(['الحلقة','المجمع','المسجد','الحالة','إجراء'],circles.map((x,i)=>[esc(x.name),esc(complexes.find(c=>c.id===x.complex_id)?.name||x.complex_id),esc(mosques.find(m=>m.id===x.mosque_id)?.name||x.mosque_id),esc(x.active?'نشطة':'موقفة'),button('تعديل','circle-'+i)]))}`;
  mosques.forEach((m,i)=>action(area,area.querySelector(`[data-action="mosque-${i}"]`),()=>editMosque(m,complexes)));
  circles.forEach((x,i)=>action(area,area.querySelector(`[data-action="circle-${i}"]`),()=>editCircle(x,complexes,mosques)));
 };
 const editMosque=(m,complexes)=>{const b=modal(m?'تعديل المسجد وإعدادات البصمة':'إضافة مسجد وموقع بصمة');const cfg=Array.isArray(m?.attendance_windows)?m.attendance_windows[0]||{}:{};const prayers=[{id:'Fajr',name:'الفجر'},{id:'Dhuhr',name:'الظهر'},{id:'Asr',name:'العصر'},{id:'Maghrib',name:'المغرب'},{id:'Isha',name:'العشاء'}];b.innerHTML=`<form><div class="form-grid two">${select('المجمع','complex_id',complexes,m?.complex_id)}${field('اسم المسجد','name','text',m?.name||'','required')}${field('خط العرض','latitude','number',m?.latitude||'','step="any" required')}${field('خط الطول','longitude','number',m?.longitude||'','step="any" required')}${field('نطاق البصمة بالمتر','radius','number',m?.radius_meters||100,'min="20" max="500" required')}${select('بداية الدوام','startPrayer',prayers,cfg.startPrayer||'Asr')}${select('نهاية الدوام','endPrayer',prayers,cfg.endPrayer||'Maghrib')}${field('سماح التأخير بالدقائق','late','number',cfg.lateAllowMinutes??15,'min="0" max="180"')}${field('حد الحضور المبكر بالدقائق','early','number',cfg.earlyArrivalMinutes??15,'min="0" max="180"')}${field('سماح الانصراف المبكر بالدقائق','leave','number',cfg.earlyLeaveMinutes??15,'min="0" max="180"')}${field('يعد غائبًا بعد بداية الدوام بـ','absent','number',cfg.absenceAfterMinutes??60,'min="0" max="360"')}${field('مهلة الانصراف بعد نهاية الدوام','grace','number',cfg.checkoutGraceMinutes??120,'min="0" max="360"')}</div><button type="button" class="button button-soft" data-action="gps">استخدام موقعي الحالي</button><button type="submit" class="button button-primary">حفظ المسجد وإعدادات البصمة</button></form>`;const form=b.querySelector('form');action(b,b.querySelector('[data-action="gps"]'),async()=>{const p=await new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:15000}));form.elements.latitude.value=p.coords.latitude;form.elements.longitude.value=p.coords.longitude});submit(form,async()=>{const config={action:'both',weekdays:['0','1','2','3','4'],start:'00:00',end:'23:59',startPrayer:val(form,'startPrayer'),endPrayer:val(form,'endPrayer'),lateAllowMinutes:Number(val(form,'late')),earlyArrivalMinutes:Number(val(form,'early')),earlyLeaveMinutes:Number(val(form,'leave')),absenceAfterMinutes:Number(val(form,'absent')),checkoutGraceMinutes:Number(val(form,'grace'))};const row={org_id:a.org_id,complex_id:val(form,'complex_id'),name:val(form,'name'),latitude:Number(val(form,'latitude')),longitude:Number(val(form,'longitude')),radius_meters:Number(val(form,'radius')),attendance_windows:[config],timezone:'Asia/Riyadh',active:true,updated_at:new Date().toISOString()};if(m)await result(sb().from('mosques').update(row).eq('id',m.id).select('id').single());else await result(sb().from('mosques').insert({id:'mosque-'+crypto.randomUUID(),...row}).select('id').single());lookupPromise=null;b.closest('dialog').close();await load();msg(root,'تم حفظ موقع المسجد وإعدادات البصمة.')})};
 const editCircle=(x,complexes,mosques)=>{const b=modal(x?'تعديل الحلقة':'إضافة حلقة');b.innerHTML=`<form><div class="form-grid two">${select('المجمع','complex_id',complexes,x?.complex_id)}${select('المسجد','mosque_id',mosques.map(m=>({id:m.id,name:m.name})),x?.mosque_id)}${field('اسم الحلقة','name','text',x?.name||'','required')}<label>نشطة<input name="active" type="checkbox" ${x?.active===false?'':'checked'}></label></div><button type="submit" class="button button-primary">حفظ الحلقة</button></form>`;const form=b.querySelector('form');submit(form,async()=>{const mosque=mosques.find(m=>m.id===val(form,'mosque_id'));if(!mosque||mosque.complex_id!==val(form,'complex_id'))throw Error('اختر مسجدًا تابعًا للمجمع نفسه');const row={org_id:a.org_id,complex_id:val(form,'complex_id'),mosque_id:mosque.id,name:val(form,'name'),active:form.elements.active.checked,updated_at:new Date().toISOString()};if(x)await result(sb().from('circles').update(row).eq('id',x.id).select('id').single());else await result(sb().from('circles').insert({id:'circle-'+crypto.randomUUID(),...row}).select('id').single());lookupPromise=null;b.closest('dialog').close();await load();msg(root,'تم حفظ الحلقة.')})};
 action(root,root.querySelector('[data-action="add-complex"]'),async()=>{const b=modal('إضافة مجمع');b.innerHTML=`<form>${field('اسم المجمع','name','text','','required')}<button type="submit" class="button button-primary">إنشاء المجمع</button></form>`;const form=b.querySelector('form');submit(form,async()=>{await result(sb().from('complexes').insert({id:'complex-'+crypto.randomUUID(),org_id:a.org_id,name:val(form,'name'),active:true}).select('id').single());lookupPromise=null;b.closest('dialog').close();await load();msg(root,'تم إنشاء المجمع، ويمكن الآن إضافة مسجد وحلقات وحسابات له.')})});
 action(root,root.querySelector('[data-action="add-mosque"]'),async()=>{const complexes=await rows('complexes','*',{active:true});editMosque(null,complexes)});
 action(root,root.querySelector('[data-action="add-circle"]'),async()=>{const [complexes,mosques]=await Promise.all([rows('complexes','*',{active:true}),rows('mosques','*',{active:true})]);editCircle(null,complexes,mosques)});
 await load()
}
async function mount(root,view){root.classList.add('sl-live');root.innerHTML=`<h1>${esc(titles[view]||'سنابل الوحي')}</h1><div class="sl-content"><p>جارٍ التحميل…</p></div>`;const b=root.querySelector('.sl-content');try{await access();b.innerHTML='';const render={dashboard,students:studentsPage,outcomes:outcomesPage,plans:plansPage,attendance:attendancePage,tests:testsPage,inquiries:reportPage,reports:statisticsPage,settings:settingsPage}[view];if(!render)throw Error('الصفحة غير متاحة');await render(b)}catch(e){msg(b,e.message,true)}}
window.SanabilLive={mount,usersPanel};window.dispatchEvent(new Event("sanabil-live-ready"));
window.addEventListener('sanabil-session-changed',()=>{lookupPromise=null;surahsPromise=null});
const style=document.createElement('style');style.textContent=`.sl-live{background:white;border:1px solid #dde5df;border-radius:20px;padding:24px;min-height:300px}.sl-toolbar{display:flex;flex-wrap:wrap;align-items:end;gap:12px;margin:15px 0}.sl-live label,.sl-dialog label{display:grid;gap:8px;font-weight:600}.sl-live input,.sl-live select,.sl-dialog input,.sl-dialog select{font:inherit;max-width:100%;min-width:0;padding:10px;border:1px solid #bdccc3;border-radius:8px;background:white}.sl-live table,.sl-dialog table{width:100%;border-collapse:collapse}.sl-live th,.sl-live td,.sl-dialog td,.sl-dialog th{padding:12px;text-align:right;border-bottom:1px solid #e2e9e5}.sl-dialog{direction:rtl;width:min(900px,94vw);max-height:90vh;border:0;border-radius:18px;padding:24px;color:#183c33}.sl-dialog::backdrop{background:#002c2580}.sl-dialog header{display:flex;align-items:center;justify-content:space-between;gap:16px}.sl-dialog fieldset{border:1px solid #ddd;border-radius:12px;margin:12px 0}.sl-live .button,.sl-dialog .button{margin:3px}.sl-message{padding:12px;background:#f3f7f4;border-radius:8px}.sl-dialog .form-grid,.sl-live .form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin:18px 0}.sl-live .table-wrap{overflow:auto}.sl-data input{width:100%;box-sizing:border-box}.sl-live .stats-grid{grid-template-columns:repeat(4,minmax(0,1fr))}@media(max-width:650px){.sl-dialog .form-grid,.sl-live .form-grid{grid-template-columns:1fr}.sl-live{padding:14px}.sl-live .stats-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media print{.topbar,.tabs,.mobile-nav,.sl-toolbar,button,.more-sheet{display:none!important}.app-content,.sl-live{margin:0!important;padding:0!important;border:0}.table-wrap{overflow:visible!important}thead{display:table-header-group}tr{break-inside:avoid}body{background:white!important}}`;document.head.append(style);
})();
